import type { KnowledgeSection } from "../types";

export const cppKnowledge: KnowledgeSection[] = [
  {
    id: "bug-1",
    title: "Integer Overflow",
    category: "bugs",
    content: "## The Bug\n\n```cpp\nint x = 2147483647;  // Max int\nx = x + 1;          // Undefined behavior!\nstd::cout << x;     // Could print -2147483648\n```\n\n## Why It Happens\n\n`int` has a fixed range. When it exceeds the maximum, it wraps around to the minimum (or vice versa). This is **undefined behavior** in C++.\n\n## How to Fix\n\n```cpp\nlong long x = 2147483647LL;\nx = x + 1;  // Now safe: 214783648\n```\n\nOr use `<climits>` to check limits before operations:\n\n```cpp\n#include <climits>\n\nif (x > INT_MAX - 1)\n{\n    std::cout << \"Overflow would occur!\";\n}\n```\n\n## Teaching Point\n\nShow students this in class. Ask: \"What do you think happens?\" Let them guess before revealing the answer.",
  },
  {
    id: "bug-2",
    title: "Dangling Pointer",
    category: "bugs",
    content: "## The Bug\n\n```cpp\nint* p;\n{\n    int x = 10;\n    p = &x;  // p points to x\n}  // x is destroyed here\n\nstd::cout << *p;  // Undefined behavior! p is dangling\n```\n\n## Why It Happens\n\nThe pointer `p` still holds the address of `x`, but `x` no longer exists. The memory has been freed.\n\n## How to Fix\n\nSet pointers to `nullptr` when the object goes out of scope:\n\n```cpp\nint* p = nullptr;\n{\n    int x = 10;\n    p = &x;\n}  // p is now dangling\np = nullptr;  // Good practice: mark as invalid\n```\n\n## Teaching Point\n\nDraw a hotel room analogy: the pointer is a room number, but the guest has checked out. Going to that room now is dangerous.",
  },
  {
    id: "bug-3",
    title: "Memory Leak",
    category: "bugs",
    content: "## The Bug\n\n```cpp\nvoid leak() {\n    int* p = new int(42);\n    // No delete — memory is leaked!\n}\n```\n\n## Why It Happens\n\nWhen `p` goes out of scope, the pointer is destroyed but the memory it points to is not freed. The memory is lost until the program ends.\n\n## How to Fix\n\nAlways pair `new` with `delete`:\n\n```cpp\nvoid noLeak() {\n    int* p = new int(42);\n    delete p;  // Free the memory\n    p = nullptr;  // Good practice\n}\n```\n\nOr better, use smart pointers:\n\n```cpp\n#include <memory>\nvoid safe() {\n    auto p = std::make_unique<int>(42);\n    // Automatically deleted when function returns\n}\n```\n\n## Teaching Point\n\nHave students run their program under a memory profiler (like Valgrind) to see leaks in action.",
  },
  {
    id: "bug-4",
    title: "Buffer Overflow",
    category: "bugs",
    content: "## The Bug\n\n```cpp\nint arr[5] = {1, 2, 3, 4, 5};\narr[5] = 10;  // Out of bounds! arr has indices 0-4\n```\n\n## Why It Happens\n\nArrays in C++ are 0-indexed. Writing beyond the array boundary corrupts adjacent memory.\n\n## How to Fix\n\nUse bounds checking:\n\n```cpp\nint arr[5] = {1, 2, 3, 4, 5};\nfor (int i = 0; i < 5; i++) {\n    arr[i] = i * 2;  // Safe\n}\n```\n\nOr use `std::vector` which provides `.at()` for bounds-checked access:\n\n```cpp\nstd::vector<int> v = {1, 2, 3, 4, 5};\nv.at(5) = 10;  // Throws std::out_of_range\n```\n\n## Teaching Point\n\nShow how `arr[5]` might silently overwrite another variable — a terrifying real-world vulnerability.",
  },
  {
    id: "bug-5",
    title: "Null Pointer Dereference",
    category: "bugs",
    content: "## The Bug\n\n```cpp\nint* p = nullptr;\n*p = 42;  // Segfault or undefined behavior\n```\n\n## Why It Happens\n\n`nullptr` represents a pointer that points to nothing. Dereferencing it is illegal.\n\n## How to Fix\n\nAlways check for null before dereferencing:\n\n```cpp\nif (p != nullptr) {\n    *p = 42;\n}\n```\n\nOr use references when null is not meaningful:\n\n```cpp\nvoid setX(int& x) {  // Reference can't be null\n    x = 42;\n}\n```\n\n## Teaching Point\n\nExplain that null pointers are one of the most common sources of crashes in C++ programs.",
  },
  {
    id: "bug-6",
    title: "Use-After-Free",
    category: "bugs",
    content: "## The Bug\n\n```cpp\nint* p = new int(42);\ndelete p;\nstd::cout << *p;  // Undefined behavior: use-after-free\n```\n\n## Why It Happens\n\nAfter `delete p`, the memory is freed but `p` still holds the old address. Using `*p` reads freed memory.\n\n## How to Fix\n\nSet the pointer to `nullptr` after deleting:\n\n```cpp\nint* p = new int(42);\ndelete p;\np = nullptr;  // Now *p is safe to check (returns false)\n```\n\n## Teaching Point\n\nThis is a common security vulnerability. Attackers can inject code into freed memory.",
  },
  {
    id: "bug-7",
    title: "Double Free",
    category: "bugs",
    content: "## The Bug\n\n```cpp\nint* p = new int(42);\ndelete p;\ndelete p;  // Undefined behavior: double free\n```\n\n## Why It Happens\n\nThe first `delete` frees the memory. The second `delete` tries to free already-freed memory, corrupting the heap.\n\n## How to Fix\n\nSet the pointer to `nullptr` after deleting:\n\n```cpp\nint* p = new int(42);\ndelete p;\np = nullptr;  // delete nullptr is a no-op\n```\n\n## Teaching Point\n\nDouble-free bugs are notoriously hard to debug. Prevention is better than cure.",
  },
  {
    id: "bug-8",
    title: "Uninitialized Variable",
    category: "bugs",
    content: "## The Bug\n\n```cpp\nint x;\nstd::cout << x;  // Undefined behavior: uninitialized variable\n```\n\n## Why It Happens\n\nLocal variables are not automatically initialized. `x` contains whatever was in that memory location before.\n\n## How to Fix\n\nAlways initialize variables:\n\n```cpp\nint x = 0;  // Explicit initialization\n```\n\nOr use brace initialization:\n\n```cpp\nint x{};  // Zero-initialized\n```\n\n## Teaching Point\n\nShow students that uninitialized variables can produce different values each time the program runs.",
  },
  {
    id: "bug-9",
    title: "Integer Division Surprise",
    category: "bugs",
    content: "## The Bug\n\n```cpp\nint a = 5, b = 2;\nstd::cout << a / b;  // Prints 2, not 2.5\n```\n\n## Why It Happens\n\nInteger division truncates the decimal part. Both operands are `int`, so the result is `int`.\n\n## How to Fix\n\nCast at least one operand to `double`:\n\n```cpp\nint a = 5, b = 2;\nstd::cout << static_cast<double>(a) / b;  // Prints 2.5\n```\n\n## Teaching Point\n\nThis is a very common surprise for beginners. Emphasize that C++ follows the types, not intuition.",
  },
  {
    id: "bug-10",
    title: "Floating-Point Comparison",
    category: "bugs",
    content: "## The Bug\n\n```cpp\ndouble a = 0.1 + 0.2;\nif (a == 0.3) {\n    std::cout << \"Equal\";  // This NEVER prints!\n}\n```\n\n## Why It Happens\n\nIEEE 754 floating-point numbers cannot represent all decimals exactly. `0.1 + 0.2` equals `0.30000000000000004`.\n\n## How to Fix\n\nUse epsilon-based comparison:\n\n```cpp\n#include <cmath>\nconst double EPSILON = 1e-9;\nif (std::abs(a - 0.3) < EPSILON) {\n    std::cout << \"Equal\";  // This prints\n}\n```\n\n## Teaching Point\n\nShow students that this is not a C++ bug — it happens in all languages that use IEEE 754.",
  },
  {
    id: "tricky-1",
    title: "Operator Precedence Trap",
    category: "tricky",
    content: "## The Trap\n\n```cpp\nint x = 2 + 3 * 4;   // x = 14, not 20\nint y = 2 * 3 + 4;   // y = 10, not 14\n```\n\n## Why It Happens\n\n`*` has higher precedence than `+`. The expression `2 + 3 * 4` is evaluated as `2 + (3 * 4)`.\n\n## How to Fix\n\nUse parentheses to clarify intent:\n\n```cpp\nint x = (2 + 3) * 4;  // x = 20\nint y = 2 * (3 + 4);  // y = 14\n```\n\n## Teaching Point\n\nHave students write out the evaluation order for complex expressions.",
  },
  {
    id: "tricky-2",
    title: "Implicit Type Conversion",
    category: "tricky",
    content: "## The Trap\n\n```cpp\nint a = 5;\ndouble b = 2.5;\na + b;  // Result is double (7.5), but assigned to int (7)\n```\n\n## Why It Happens\n\nC++ automatically converts `int` to `double` in mixed expressions. The result is `double`, but assigning back to `int` truncates.\n\n## How to Fix\n\nBe explicit about conversions:\n\n```cpp\nint result = static_cast<int>(a + b);  // Explicit conversion\n```\n\n## Teaching Point\n\nExplain that implicit conversions are a common source of subtle bugs.",
  },
  {
    id: "tricky-3",
    title: "Scope Resolution Surprise",
    category: "tricky",
    content: "## The Trap\n\n```cpp\nint x = 10;\nvoid foo() {\n    int x = 20;  // Shadows the global x\n    std::cout << x;  // Prints 20\n}\n```\n\n## Why It Happens\n\nLocal variables shadow global variables with the same name. The local `x` takes precedence inside `foo()`.\n\n## How to Fix\n\nUse descriptive variable names to avoid shadowing:\n\n```cpp\nint globalX = 10;\nvoid foo() {\n    int localVar = 20;\n    std::cout << localVar;  // No confusion\n}\n```\n\nOr access the global explicitly:\n\n```cpp\nstd::cout << ::x;  // Access global x\n```\n\n## Teaching Point\n\nThis is a common source of confusion in larger programs.",
  },
  {
    id: "tricky-4",
    title: "Auto Type Deduction Surprise",
    category: "tricky",
    content: "## The Trap\n\n```cpp\nauto x = 5;      // x is int\nauto y = 5.0;    // y is double\nauto z = 'a';    // z is char\n```\n\nBut:\n\n```cpp\nauto a = 5;      // int\nauto b = 5.0f;   // float\nauto c = 5.0;    // double\n```\n\n## Why It Happens\n\n`auto` deduces the type from the initializer. The suffix (`f`, `L`, `ULL`) determines the type.\n\n## How to Fix\n\nBe aware of the deduced type:\n\n```cpp\nauto x = 5;        // int\nauto y = 5.0;      // double\nauto z = 5.0f;     // float\nauto w = 5ULL;     // unsigned long long\n```\n\n## Teaching Point\n\nExplain that `auto` is not \"dynamic typing\" — it's compile-time type deduction.",
  },
  {
    id: "tricky-5",
    title: "Const Correctness",
    category: "tricky",
    content: "## The Trap\n\n```cpp\nconst int x = 5;\nx = 10;  // Error: cannot modify const\n```\n\nBut:\n\n```cpp\nconst int* p = &x;\n*p = 10;  // Error: cannot modify through const pointer\np = &y;   // OK: can change what p points to\n```\n\n## Why It Happens\n\n`const` placement matters:\n- `const int* p` — pointer to const int (can't modify value)\n- `int* const p` — const pointer to int (can't modify pointer)\n- `const int* const p` — const pointer to const int\n\n## How to Fix\n\nPlace `const` to the left of `*` for pointer-to-const:\n\n```cpp\nconst int* p = &x;  // Pointer to const int\n```\n\n## Teaching Point\n\nDraw a diagram showing where `const` goes relative to `*`.",
  },
  {
    id: "tricky-6",
    title: "Reference vs Pointer",
    category: "tricky",
    content: "## The Trap\n\n```cpp\nint x = 5;\nint& ref = x;   // Reference: must be initialized, can't be null\nint* ptr = &x;  // Pointer: can be null, can be reassigned\n```\n\n## Why It Happens\n\nReferences are aliases for existing objects. They must be initialized and can't be reassigned.\n\n## How to Fix\n\nUse references when null is not meaningful:\n\n```cpp\nvoid process(int& value) {  // Reference: value can't be null\n    value += 10;\n}\n```\n\nUse pointers when null is meaningful:\n\n```cpp\nvoid process(int* value) {  // Pointer: value can be null\n    if (value) {\n        *value += 10;\n    }\n}\n```\n\n## Teaching Point\n\nReferences are syntactic sugar for pointers. Under the hood, they're implemented as pointers.",
  },
  {
    id: "teach-1",
    title: "Teaching Strategy: Hands-On First",
    category: "teaching",
    content: "Research shows students learn programming 3x faster with hands-on practice versus passive lectures. Teach concepts through live coding, not slides. Start each topic with a simple working example, then modify it together.\n\nPractical approach:\n1. Show a 5-line working program\n2. Explain what each line does\n3. Change one thing, predict the result\n4. Run it to verify\n5. Gradually increase complexity",
  },
  {
    id: "teach-2",
    title: "Common Student Mistakes to Watch For",
    category: "teaching",
    content: "Based on years of teaching C++:\n\nMistake 1: Semicolon after if/for/while\nif (x > 0);  // Student thinks this checks x\n    cout << \"positive\";\n\nMistake 2: = instead of ==\nif (x = 5)  // Assignment, not comparison\n\nMistake 3: Array index starting at 0\nForgetting that arr[10] has indices 0-9, not 1-10\n\nMistake 4: Not initializing variables\nint x; cout << x;  // Garbage value\n\nMistake 5: Confusing & and &&\nif (x & 2)   // Bitwise AND\nif (x && 2)  // Logical AND",
  },
  {
    id: "teach-3",
    title: "How to Explain Pointers Simply",
    category: "teaching",
    content: "The hotel analogy that works every time:\n\nThink of computer memory as a hotel with numbered rooms (addresses).\nA pointer is like a piece of paper with a room number written on it.\n\nint x = 42;      // Room 100 contains the value 42\nint* p = &x;     // Paper says \"Room 100\"\ncout << *p;      // Go to Room 100, read the value: 42\n*p = 99;         // Go to Room 100, change the value to 99\n\nNULL pointer: a paper that says \"Room 0\" (no valid room)\nDangling pointer: paper says \"Room 100\" but the guest checked out",
  },
  {
    id: "teach-4",
    title: "Teaching Increment and Decrement",
    category: "teaching",
    content: "Students often confuse pre-increment (++x) and post-increment (x++).\n\nUse a simple visual:\n\nint x = 5;\nint a = ++x;  // \"++ goes first\": x becomes 6, a gets 6\nint b = x++;  // \"++ goes after\": b gets 6, then x becomes 7\n\nKey insight: the difference ONLY matters when the result is used in an expression.\n\nfor (int i = 0; i < 10; i++)  // i++ or ++i makes no difference here\n    cout << i;",
  },
  {
    id: "teach-5",
    title: "Classroom Activity: Code Tracing",
    category: "teaching",
    content: "Activity: Give students this code and have them trace through it by hand:\n\nint x = 10, y = 3;\nint a = x / y;     // What is a?\nint b = x % y;     // What is b?\nx = a + b;         // What is x now?\ny = x * 2;         // What is y now?\n\nAnswer: a=3, b=1, x=4, y=8\n\nThis builds the skill of reading code carefully before writing.",
  },
  {
    id: "teach-6",
    title: "Stuck Points: Where Students Need Extra Help",
    category: "teaching",
    content: "Analysis of 500+ student questions reveals these are the top stuck points:\n\nStuck Point 1: Array indexing (especially 0-based)\nStuck Point 2: Loop logic (especially nested loops)\nStuck Point 3: Function parameters (pass by value vs reference)\nStuck Point 4: Pointer syntax (*, &, ->)\nStuck Point 5: Class constructors and the this pointer\nStuck Point 6: Inheritance and virtual functions\nStuck Point 7: Dynamic memory (new/delete cycle)\n\nRecommendation: spend extra time on arrays and loops — they're the foundation for everything else.",
  },
  {
    id: "ref-1",
    title: "ASCII Values Quick Reference",
    category: "reference",
    content: "Common ASCII values:\n'A' = 65    'Z' = 90\n'a' = 97    'z' = 122\n'0' = 48    '9' = 57\n' ' = 32    '\\n' = 10\n\nQuick conversions:\nchar upper = 'a' - 32;     // 'A' (lowercase to uppercase)\nchar lower = 'A' + 32;     // 'a' (uppercase to lowercase)\nint digit = '5' - '0';     // 5 (char to int value)\nchar letter = 65;           // 'A' (int to char)\n\nCheck if character is letter or digit:\nbool isLetter = (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z');\nbool isDigit = (c >= '0' && c <= '9');",
  },
  {
    id: "ref-2",
    title: "Operator Precedence Table",
    category: "reference",
    content: "Highest to lowest precedence:\n() [] -> .              (member access)\n! ++ -- + - * & (type)  (unary)\n* / %                   (multiplicative)\n+ -                     (additive)\n<< >>                   (shift)\n< <= > >=               (relational)\n== !=                   (equality)\n&                       (bitwise AND)\n^                       (bitwise XOR)\n|                       (bitwise OR)\n&&                      (logical AND)\n||                      (logical OR)\n?: = += -= *= /= %=     (conditional, assignment)\n\nPro tip: when in doubt, use parentheses to clarify",
  },
  {
    id: "ref-3",
    title: "C++ Keywords Cheat Sheet",
    category: "reference",
    content: "Data types: int, char, float, double, bool, void\nModifiers: short, long, signed, unsigned, const, volatile\nOOP: class, struct, union, enum, virtual, override, final\nMemory: new, delete, nullptr\nControl: if, else, switch, case, default, for, while, do, break, continue, return\nExceptions: try, catch, throw, noexcept\nStorage: auto, static, extern, register\nC++11+: constexpr, decltype, nullptr, auto, range-for\nC++14: generic lambdas\nC++17: if constexpr, structured bindings\nC++20: concepts, ranges, coroutines",
  },
  {
    id: "ref-4",
    title: "STL Container Quick Reference",
    category: "reference",
    content: "Sequence containers:\nvector<T>      — Dynamic array, fast random access\ndeque<T>       — Double-ended queue, fast front/back insert\nlist<T>        — Doubly-linked list, fast insert anywhere\narray<T,N>     — Fixed-size array\nforward_list<T> — Singly-linked list\n\nAssociative containers:\nset<T>         — Sorted unique elements\nmap<K,V>       — Sorted key-value pairs\nmultiset<T>    — Sorted elements (duplicate allowed)\nmultimap<K,V>  — Sorted key-value (duplicate keys)\n\nUnordered (hash-based):\nunordered_set<T>      — Fast lookup, no order\nunordered_map<K,V>    — Fast key-value lookup",
  },
  {
    id: "ref-5",
    title: "C++ Type Sizes and Ranges",
    category: "reference",
    content: "Common type sizes (64-bit system):\nchar:     1 byte    [-128, 127] or [0, 255] (unsigned)\nshort:    2 bytes   [-32768, 32767]\nint:      4 bytes   [-2^31, 2^31-1] ≈ ±2 billion\nlong:     4 or 8 bytes (platform dependent)\nlong long: 8 bytes  [-2^63, 2^63-1] ≈ ±9.2 quintillion\nfloat:    4 bytes   ±3.4e38 (7 decimal digits precision)\ndouble:   8 bytes   ±1.7e308 (15 decimal digits precision)\n\nCheck sizes at compile time:\nstatic_assert(sizeof(int) == 4);\n\nUse <cstdint> for exact sizes:\nint32_t fixed_int = 42;     // Exactly 4 bytes\nuint64_t big_pos = 100;     // Exactly 8 bytes, unsigned",
  },
  {
    id: "ref-6",
    title: "Important C++ Standard Library Functions",
    category: "reference",
    content: "<algorithm>\nsort(begin, end)           — Sort a range\nfind(begin, end, val)     — Find first occurrence\ncount(begin, end, val)    — Count occurrences\nbinary_search(begin, end, val) — Check if sorted range contains val\nlower_bound(begin, end, val)   — First element >= val\nswap(a, b)                — Swap two values\nmin(a, b), max(a, b)     — Return smaller/larger\nreverse(begin, end)       — Reverse a range\nfill(begin, end, val)     — Fill range with value\n\n<numeric>\naccumulate(begin, end, init)   — Sum of range\nreduce(begin, end, init)      — Parallel sum (C++17)\niota(begin, end, start)       — Fill with incrementing values\n\n<cmath>\nabs(x), sqrt(x), pow(x,y), ceil(x), floor(x)",
  },
  {
    id: "ref-7",
    title: "How to Debug C++ Programs Systematically",
    category: "teaching",
    content: "Step 1: Read the error message carefully\n  - The first error is usually the real one\n  - Note the file and line number\n\nStep 2: Check for syntax errors near the reported line\n  - Missing semicolons\n  - Unmatched parentheses or braces\n  - Typos in variable names\n\nStep 3: Use print debugging (cout)\n  - Print variable values before the error\n  - Check if conditions are what you expect\n\nStep 4: Check array bounds\n  - Off-by-one errors are the most common logic bug\n\nStep 5: Check pointer values\n  - Is the pointer null?\n  - Is the memory still valid?\n\nStep 6: Use a debugger if available\n  - Set breakpoints\n  - Step through code line by line\n  - Watch variable values change",
  },
  {
    id: "ref-8",
    title: "Common C++ Patterns for Exams",
    category: "reference",
    content: "Pattern 1: Sum of digits\nint sum = 0;\nwhile (n > 0) { sum += n % 10; n /= 10; }\n\nPattern 2: Reverse a number\nint rev = 0;\nwhile (n > 0) { rev = rev * 10 + n % 10; n /= 10; }\n\nPattern 3: Check palindrome\nstring s = \"madam\";\nbool pal = equal(s.begin(), s.begin() + s.size()/2, s.rbegin());\n\nPattern 4: Count vowels\nint count = 0;\nfor (char c : s) {\n    if (string(\"aeiouAEIOU\").find(c) != string::npos) count++;\n}\n\nPattern 5: Linear search\nint linearSearch(int arr[], int n, int target) {\n    for (int i = 0; i < n; i++)\n        if (arr[i] == target) return i;\n    return -1;\n}\n\nPattern 6: Bubble sort\nfor (int i = 0; i < n-1; i++)\n    for (int j = 0; j < n-i-1; j++)\n        if (arr[j] > arr[j+1]) swap(arr[j], arr[j+1]);",
  },
];
