import type { NoteSection } from "../types";

export const cppNotes: NoteSection[] = [
  {
    id: "course-introduction",
    subject: "cpp",
    title: "Course Introduction",
    content: "Welcome to C++ Programming!\n\nWhat You Will Learn:\n- fundamentals of programming in C++\n- variables, data types, operators\n- control flow (if/else, loops)\n- functions and modular programming\n- arrays, strings, pointers\n- object-oriented programming (classes, objects, inheritance, polymorphism)\n- file handling and STL basics\n- memory management and best practices\n\nHow This Course Works:\n- Each topic has lecture notes, examples, and practice problems\n- Coding examples are editable and runnable\n- Quizzes test your understanding after each topic\n- A final project ties everything together\n\nPrerequisites:\n- Basic computer skills (using a keyboard, mouse, files)\n- No prior programming experience required\n- Willingness to practice and experiment\n\nLet's begin!",
    difficulty: "beginner",
    estimatedMinutes: 5,
    topic: "basics",
  },
  {
    id: "what-is-programming",
    subject: "cpp",
    title: "What is Programming?",
    content: "Programming is the process of giving instructions to a computer to perform a task.\n\nReal-World Analogy:\nThink of a recipe for cooking. The recipe lists step-by-step instructions. A program is a recipe for the computer.\n\nKey Terms:\n- Algorithm: A step-by-step procedure to solve a problem\n- Source Code: The human-readable instructions you write\n- Compiler: Translates your code into machine language\n- Bug: An error in the program\n- Debugging: Finding and fixing bugs\n\nExample Algorithm (Making Tea):\n1. Boil water\n2. Put tea bag in cup\n3. Pour hot water into cup\n4. Wait 3 minutes\n5. Remove tea bag\n6. Add sugar if desired\n\nProgramming languages (C++, Python, Java) are tools to express these instructions in a way the computer understands.",
    difficulty: "beginner",
    estimatedMinutes: 8,
    topic: "basics",
  },
  {
    id: "what-is-cpp",
    subject: "cpp",
    title: "What is C++?",
    content: "C++ is a general-purpose programming language created by Bjarne Stroustrup in 1979 as an extension of the C language.\n\nWhy Learn C++?\n- High performance (used in game engines, browsers, operating systems)\n- Foundational (understanding C++ makes other languages easier)\n- Industry standard (used in finance, gaming, embedded systems, robotics)\n- Direct memory control (unlike Python or Java)\n\nWhere is C++ Used?\n- Game engines: Unreal Engine, Unity (partially)\n- Browsers: Chrome, Firefox\n- Operating systems: Windows, macOS parts\n- Databases: MongoDB, MySQL\n- Embedded systems: IoT devices, automotive\n- High-frequency trading systems\n\nC++ vs Other Languages:\n- C++: Fast, manual memory management, steep learning curve\n- Python: Easy to learn, slower, automatic memory management\n- Java: Portable, garbage collected, verbose syntax\n\nC++ Standard Versions:\n- C++98/03: Original standard\n- C++11: Modern features (auto, lambda, smart pointers)\n- C++14/17: Incremental improvements\n- C++20/23: Latest features (concepts, ranges, coroutines)",
    difficulty: "beginner",
    estimatedMinutes: 10,
    topic: "basics",
  },
  {
    id: "compiler",
    subject: "cpp",
    title: "Compiler",
    content: "A compiler translates your human-readable C++ code into machine code that the computer's processor can execute.\n\nHow Compilation Works:\n1. Preprocessing: Handles #include, #define, macros\n2. Compilation: Converts source code to assembly\n3. Assembly: Converts assembly to object code\n4. Linking: Combines object files into executable\n\nPopular C++ Compilers:\n- GCC (g++): Free, Linux default, widely used\n- Clang: Fast, good error messages, used by LLVM\n- MSVC: Microsoft Visual C++, Windows default\n- Intel C++: Optimized for Intel processors\n\nHow to Compile (Command Line):\ng++ -o program program.cpp\n\nHow to Compile (IDE):\n- Visual Studio: Build -> Build Solution (F7)\n- Code:: Shift+F9 or Build menu\n\nCommon Compiler Errors:\n- Missing semicolon at end of statement\n- Undefined variable (typo or scope issue)\n- Missing #include directive\n- Type mismatch in assignment",
    difficulty: "beginner",
    estimatedMinutes: 10,
    topic: "basics",
  },
  {
    id: "installing-cpp",
    subject: "cpp",
    title: "Installing C++",
    content: "You need two things: a compiler and a code editor.\n\nOption 1: Visual Studio (Windows)\n1. Download Visual Studio Community from visualstudio.com\n2. During installation, select 'Desktop development with C++'\n3. This includes the MSVC compiler and debugger\n\nOption 2: Code::Blocks (All Platforms)\n1. Download from codeblocks.org\n2. Choose the version with MinGW compiler\n3. Install and configure the compiler path\n\nOption 3: Online Compiler (No Installation)\n- repl.it: https://replit.com\n- OnlineGDB: https://onlinegdb.com\n- Compiler Explorer: https://godbolt.org\n\nVerifying Installation:\n1. Open terminal/command prompt\n2. Type: g++ --version\n3. You should see the compiler version\n\nWriting Your First File:\n1. Create a file named main.cpp\n2. Write your code\n3. Compile: g++ -o main main.cpp\n4. Run: ./main (Linux/Mac) or main.exe (Windows)\n\nRecommended Setup for This Course:\n- Visual Studio Code with C/C++ extension\n- MinGW or WSL for Windows\n- Terminal for compiling and running",
    difficulty: "beginner",
    estimatedMinutes: 15,
    topic: "basics",
  },
  {
    id: "first-cpp-program",
    subject: "cpp",
    title: "First C++ Program",
    content: "#include <iostream>\nusing namespace std;\n\nint main() {\n    cout << \"Hello, World!\" << endl;\n    return 0;\n}\n\nLine-by-Line Explanation:\n\n#include <iostream>\nThis includes the input/output stream library. It gives you access to cout (output) and cin (input).\n\nusing namespace std;\nThis allows you to use cout instead of std::cout. In larger projects, avoid this and use std:: explicitly.\n\nint main() {\nThe main function. Every C++ program must have exactly one main function. Execution starts here.\n\ncout << \"Hello, World!\" << endl;\nOutputs text to the screen. << is the insertion operator. endl adds a newline.\n\nreturn 0;\nReturns 0 to the operating system, indicating successful execution.\n}\n\nCompiling and Running:\ng++ -o hello hello.cpp\n./hello\nOutput: Hello, World!",
    difficulty: "beginner",
    estimatedMinutes: 10,
    topic: "basics",
  },
  {
    id: "printing-output",
    subject: "cpp",
    title: "Printing Output",
    content: "In C++, you use cout to print output to the screen.\n\nBasic Syntax:\ncout << \"Hello\";           // Prints Hello\ncout << \"Hello\" << endl;   // Prints Hello followed by newline\ncout << 42;                 // Prints 42\ncout << 3.14;              // Prints 3.14\n\nPrinting Multiple Things:\ncout << \"Name: \" << \"Alice\" << endl;\ncout << \"Age: \" << 20 << endl;\nOutput:\nName: Alice\nAge: 20\n\nPrinting Special Characters:\ncout << \"Line1\\nLine2\";     // \\n is newline\ncout << \"Tab\\tHere\";        // \\t is tab\ncout << \"Quote: \\\"Hi\\\"\";    // \\\" prints a quote\n\nPrinting with Variables (Preview):\nint age = 20;\ncout << \"Age: \" << age;   // Will learn more in Variables topic\n\nFormatting Output:\n#include <iomanip>\ncout << fixed << setprecision(2) << 3.14159;  // Prints 3.14\ncout << setw(10) << right << 42;              // Prints '        42' (right-aligned in 10 chars)\n\nCommon Mistakes:\n- Forgetting << between items\ncout << \"Hello\" \"World\";  // Error!\ncout << \"Hello\" << \"World\";  // Correct",
    difficulty: "beginner",
    estimatedMinutes: 10,
    topic: "basics",
  },
  {
    id: "comments",
    subject: "cpp",
    title: "Comments",
    content: "Comments are notes in your code that the compiler ignores. They help humans understand the code.\n\nSingle-Line Comment:\n// This is a comment\nint x = 5;  // This is also a comment\n\nMulti-Line Comment:\n/* This is a\n   multi-line comment\n   used for longer explanations */\n\nWhen to Use Comments:\n- Explain WHY something is done (not WHAT)\n- Mark sections of code\n- Disable code temporarily during debugging\n- Document functions and classes (or use docstrings)\n\nGood Comments:\n// Calculate total price including tax\nfinalPrice = price * (1 + taxRate);\n\nBad Comments (redundant):\n// increment i by 1\ni++;  // This is obvious and adds no value\n\nDocumentation Comments:\n// Function: calculateAverage\n// Purpose: Compute the average of an array of numbers\n// Parameters: arr[] - array of doubles, size - number of elements\n// Returns: double - the average value\ndouble calculateAverage(double arr[], int size) {\n    // ...\n}",
    difficulty: "beginner",
    estimatedMinutes: 5,
    topic: "basics",
  },
  {
    id: "variables",
    subject: "cpp",
    title: "Variables",
    content: "A variable is a named storage location in memory that holds a value.\n\nDeclaring Variables:\ndata_type variable_name = value;\n\nExamples:\nint age = 20;              // Integer\ndouble salary = 50000.50;  // Floating-point\nchar grade = 'A';          // Single character\nbool isStudent = true;     // Boolean (true/false)\nstring name = \"Alice\";    // Text (requires #include <string>)\n\nVariable Naming Rules:\n- Must start with a letter or underscore\n- Can contain letters, digits, underscores\n- Case-sensitive (age, Age, AGE are different)\n- Cannot use C++ keywords (int, return, etc.)\n\nNaming Conventions:\n- camelCase for variables: myVariable, studentCount\n- UPPER_SNAKE for constants: MAX_SIZE, PI\n- PascalCase for classes: Student, BankAccount\n\nInitialization Styles:\nint x = 10;      // Copy initialization\nint y(10);       // Direct initialization\nint z{10};       // Brace initialization (C++11, preferred)\nint w{};         // Value initialization (sets to 0)\n\nCommon Mistakes:\n- Using a variable before declaring it\n- Mixing types: int x = \"hello\"; // Error!\n- Forgetting to initialize (garbage value)",
    difficulty: "beginner",
    estimatedMinutes: 10,
    topic: "basics",
  },
  {
    id: "data-types",
    subject: "cpp",
    title: "Data Types",
    content: "Data types tell the compiler what kind of value a variable holds and how much memory it uses.\n\nFundamental Types:\nint        — Whole numbers (typically 4 bytes)\n           Range: -2,147,483,648 to 2,147,483,647\nfloat      — Decimal numbers (4 bytes, ~7 decimal digits)\ndouble     — Decimal numbers (8 bytes, ~15 decimal digits)\nchar       — Single character (1 byte)\nbool       — true or false (1 byte)\nvoid       — No value (used for functions that return nothing)\n\nType Modifiers:\nshort int  — Smaller integer (2 bytes)\nlong int   — Larger integer (4 or 8 bytes)\nsigned     — Can be positive or negative (default)\nunsigned   — Only positive (doubles the positive range)\n\nSize of Types:\n#include <iostream>\n#include <climits>\nusing namespace std;\n\nint main() {\n    cout << \"int: \" << sizeof(int) << \" bytes\" << endl;\n    cout << \"float: \" << sizeof(float) << \" bytes\" << endl;\n    cout << \"double: \" << sizeof(double) << \" bytes\" << endl;\n    cout << \"char: \" << sizeof(char) << \" bytes\" << endl;\n    return 0;\n}\n\nType Conversions:\nint x = 7;\ndouble y = x;     // Implicit: int to double (y = 7.0)\nint z = 3.9;      // Implicit: double to int (z = 3, truncates)\n\nExplicit Conversion (Casting):\ndouble pi = 3.14;\nint trunc = static_cast<int>(pi);  // trunc = 3 (preferred C++ style)\nint oldStyle = (int)pi;            // C-style (avoid in C++)",
    difficulty: "beginner",
    estimatedMinutes: 12,
    topic: "basics",
  },
  {
    id: "character-vs-string",
    subject: "cpp",
    title: "Character vs String",
    content: "char vs std::string — they look similar but work differently.\n\nchar — Single Character:\nchar ch = 'A';        // Single character in single quotes\nchar digit = '5';     // The character '5', not the number 5\nchar space = ' ';     // A space character\n\nchar is a primitive type (1 byte). It stores an ASCII value.\nASCII: 'A' = 65, 'a' = 97, '0' = 48\n\nstd::string — Text (Multiple Characters):\n#include <string>\nstring name = \"Alice\";       // Double quotes for strings\nstring empty = \"\";           // Empty string\nstring greeting = \"Hello\";  // Any length of text\n\nstring is a class (requires #include <string>). It manages memory automatically.\n\nCommon String Operations:\nstring s = \"Hello\";\ns.length();      // 5 (number of characters)\ns[0];            // 'H' (first character)\ns.empty();       // false\ns + \" World\";   // \"Hello World\" (concatenation)\ns.substr(1, 3);  // \"ell\" (substring)\n\nchar vs string — Key Differences:\nchar: single quotes, 1 byte, primitive\nstring: double quotes, dynamic size, class\n\nCommon Mistakes:\nchar c = \"A\";     // Error: cannot assign string to char\nstring s = 'A';   // Error: cannot assign char to string (usually)\nchar c = 'A';     // Correct\nstring s = \"A\";   // Correct",
    difficulty: "beginner",
    estimatedMinutes: 10,
    topic: "basics",
  },
  {
    id: "constants",
    subject: "cpp",
    title: "Constants",
    content: "Constants are variables whose values cannot be changed after initialization.\n\nWhy Use Constants?\n- Prevent accidental modification of important values\n- Make code more readable (PI instead of 3.14159)\n- Easier to maintain (change value in one place)\n\nDeclaring Constants:\nconst double PI = 3.14159265358979;\nconst int MAX_STUDENTS = 30;\nconst string SCHOOL_NAME = \"Tech University\";\n\nconst vs #define:\n// Old C style (avoid)\n#define PI 3.14159\n\n// C++ style (preferred)\nconst double PI = 3.14159;\n\nconst is better because:\n- Type-safe (compiler checks types)\n- Respects scope (local to block)\n- Debuggable (appears in debugger)\n\nconstexpr (Compile-Time Constant):\nconstexpr int MAX_SIZE = 100;      // Must be initialized with constant expression\nconstexpr double gravity = 9.81;\n\nconstexpr is evaluated at compile time, making it slightly faster.\n\nNaming Convention:\n- UPPER_SNAKE_CASE for constants\n- Example: MAX_SIZE, PI, DEFAULT_VALUE\n\nCommon Mistakes:\nconst int x;\nx = 10;       // Error: cannot modify const\nconst int y = 10;\ny = 20;       // Error: cannot modify const",
    difficulty: "beginner",
    estimatedMinutes: 8,
    topic: "basics",
  },
  {
    id: "input",
    subject: "cpp",
    title: "Input",
    content: "In C++, you use cin to read input from the user.\n\nBasic Input:\n#include <iostream>\nusing namespace std;\n\nint main() {\n    int age;\n    cout << \"Enter your age: \";\n    cin >> age;  // >> is the extraction operator\n    cout << \"You are \" << age << \" years old.\" << endl;\n    return 0;\n}\n\nReading Different Types:\nint x;\ncin >> x;           // Read integer\ndouble y;\ncin >> y;           // Read double\nchar c;\ncin >> c;           // Read single character\nstring name;\ncin >> name;        // Read word (stops at space)\n\nReading Full Lines:\nstring fullName;\ncout << \"Enter full name: \";\ncin >> fullName;        // Only reads up to first space!\nc getline(cin, fullName);  // Reads entire line including spaces\n\nMultiple Inputs:\nint a, b;\ncout << \"Enter two numbers: \";\ncin >> a >> b;  // Reads both numbers\n\nInput Validation:\nint age;\ncout << \"Enter age: \";\nwhile (!(cin >> age) || age < 0 || age > 150) {\n    cin.clear();           // Clear error state\n    cin.ignore(1000, '\\n'); // Discard bad input\n    cout << \"Invalid age. Try again: \";\n}\n\nCommon Mistakes:\n- Using cin >> for strings with spaces (use getline)\n- Not checking for invalid input\n- Mixing cin >> and getline (leave \\n in buffer)",
    difficulty: "beginner",
    estimatedMinutes: 10,
    topic: "basics",
  },
  {
    id: "example-student-information",
    subject: "cpp",
    title: "Example - Student Information",
    content: "Complete program combining variables, input, and output:\n\n#include <iostream>\n#include <string>\nusing namespace std;\n\nint main() {\n    // Declare variables\n    string name;\n    int age;\n    double gpa;\n    char grade;\n\n    // Get input\n    cout << \"Enter student name: \";\n    getline(cin, name);\n\n    cout << \"Enter age: \";\n    cin >> age;\n\n    cout << \"Enter GPA: \";\n    cin >> gpa;\n\n    cout << \"Enter grade (A-F): \";\n    cin >> grade;\n\n    // Display output\n    cout << \"\\n=== Student Information ===\" << endl;\n    cout << \"Name: \" << name << endl;\n    cout << \"Age: \" << age << endl;\n    cout << \"GPA: \" << gpa << endl;\n    cout << \"Grade: \" << grade << endl;\n\n    // Simple computation\n    cout << \"\\nIn 4 years, \" << name << \" will be \" << age + 4 << \" years old.\" << endl;\n\n    return 0;\n}\n\nExample Run:\nEnter student name: Alice Smith\nEnter age: 20\nEnter GPA: 3.8\nEnter grade (A-F): A\n\n=== Student Information ===\nName: Alice Smith\nAge: 20\nGPA: 3.8\nGrade: A\n\nIn 4 years, Alice Smith will be 24 years old.",
    difficulty: "beginner",
    estimatedMinutes: 10,
    topic: "basics",
  },
  {
    id: "arithmetic-operators",
    subject: "cpp",
    title: "Arithmetic Operators",
    content: "C++ provides these arithmetic operators:\n\n+   Addition:        a + b\n-   Subtraction:     a - b\n*   Multiplication:  a * b\n/   Division:        a / b\n%   Modulus:         a % b (remainder)\n\nExamples:\nint a = 10, b = 3;\na + b;   // 13\na - b;   // 7\na * b;   // 30\na / b;   // 3 (integer division, truncates)\na % b;   // 1 (remainder of 10/3)\n\nInteger Division:\n10 / 3 = 3 (not 3.333)\n7 / 2 = 3\n-7 / 2 = -3 (truncates toward zero)\n\nModulus with Negative Numbers:\n7 % 3 = 1\n-7 % 3 = -1 (sign follows dividend)\n7 % -3 = 1\n\nFloating-Point Division:\ndouble a = 10.0, b = 3.0;\na / b;   // 3.33333 (not 3)\n\nOperator Precedence:\n* / % have higher precedence than + -\nSo: 2 + 3 * 4 = 14, not 20\nUse parentheses to clarify: (2 + 3) * 4 = 20",
    difficulty: "beginner",
    estimatedMinutes: 8,
    topic: "operators",
  },
  {
    id: "integer-division",
    subject: "cpp",
    title: "Integer Division",
    content: "Integer division is a common source of bugs for beginners.\n\nThe Rule:\nWhen both operands are integers, the result is an integer (decimal part is discarded).\n\nExamples:\n7 / 2 = 3 (not 3.5)\n10 / 3 = 3 (not 3.333)\n-7 / 2 = -3 (truncates toward zero)\n\nHow to Get Decimal Results:\nCast at least one operand to double:\n\ndouble result = static_cast<double>(7) / 2;  // 3.5\nOr:\ndouble result = 7.0 / 2;  // 3.5\nOr:\ndouble result = 7 / 2.0;  // 3.5\n\nCommon Bug:\nint average = (a + b) / 2;  // Truncates!\n// If a=5, b=6: (5+6)/2 = 11/2 = 5 (not 5.5)\n\nFix:\ndouble average = static_cast<double>(a + b) / 2;  // 5.5\n\nPractice:\nWhat is the output?\ncout << 15 / 4;      // 3\ncout << 15.0 / 4;    // 3.75\ncout << 15 / 4.0;    // 3.75\ncout << static_cast<double>(15) / 4;  // 3.75",
    difficulty: "beginner",
    estimatedMinutes: 8,
    topic: "operators",
  },
  {
    id: "assignment-operators",
    subject: "cpp",
    title: "Assignment Operators",
    content: "Assignment operators store values in variables.\n\nBasic Assignment:\nint x = 10;  // x is now 10\n\nCompound Assignment Operators:\n+=   x += 5;   // x = x + 5\n-=   x -= 3;   // x = x - 3\n*=   x *= 2;   // x = x * 2\n/=   x /= 4;   // x = x / 4\n%=   x %= 3;   // x = x % 3\n\nExamples:\nint x = 10;\nx += 5;    // x = 15\nx -= 3;    // x = 12\nx *= 2;    // x = 24\nx /= 4;    // x = 6\nx %= 4;    // x = 2\n\nWhy Use Compound Operators?\n1. Shorter: x += 5 vs x = x + 5\n2. Clearer intent\n3. Sometimes more efficient (compiler optimization)\n\nAssignment is an Expression:\nint a, b;\na = b = 10;  // Right-to-left: b=10, then a=10\n\nCommon Mistakes:\n== vs =:\nif (x = 5) { ... }   // Bug: assigns 5 to x, always true\nif (x == 5) { ... }  // Correct: compares x to 5\n\nModern compilers warn about assignment in conditions.",
    difficulty: "beginner",
    estimatedMinutes: 8,
    topic: "operators",
  },
  {
    id: "increment-and-decrement",
    subject: "cpp",
    title: "Increment and Decrement",
    content: "The ++ and -- operators add or subtract 1 from a variable.\n\nBasic Usage:\nint x = 5;\nx++;    // x is now 6 (post-increment)\nx--;    // x is now 5 (post-decrement)\n\nPre vs Post:\nint x = 5;\nint a = ++x;  // Pre-increment: x becomes 6 first, then a gets 6\nint b = x++;  // Post-increment: b gets 6 first, then x becomes 7\n\nSummary:\n++x: increment, then use (pre)\nx++: use, then increment (post)\n--x: decrement, then use (pre)\nx--: use, then decrement (post)\n\nIn Loops (Doesn't Matter):\nfor (int i = 0; i < 10; i++) { ... }  // i++ is fine\nfor (int i = 0; i < 10; ++i) { ... }  // ++i is also fine\n// No difference here because the result isn't used in the expression\n\nIn Expressions (Matters):\nint x = 5;\nint y = x++ + 3;  // y = 5 + 3 = 8, then x = 6\nint z = ++x + 3;  // x = 7 first, then z = 7 + 3 = 10\n\nBest Practice:\n- Use i++ in for loops (conventional)\n- Use ++i when the result is used in an expression (clearer intent)\n- Avoid complex expressions with ++ and -- (hard to read)",
    difficulty: "beginner",
    estimatedMinutes: 8,
    topic: "operators",
  },
  {
    id: "relational-operators",
    subject: "cpp",
    title: "Relational Operators",
    content: "Relational operators compare two values and return true or false.\n\nOperators:\n==   Equal to\n!=   Not equal to\n>    Greater than\n<    Less than\n>=   Greater than or equal to\n<=   Less than or equal to\n\nExamples:\nint a = 10, b = 20;\na == b;   // false (10 is not equal to 20)\na != b;   // true (10 is not equal to 20)\na > b;    // false (10 is not greater than 20)\na < b;    // true (10 is less than 20)\na >= b;   // false (10 is not >= 20)\na <= b;   // true (10 is <= 20)\n\nUsing in Conditions:\nif (a > b) {\n    cout << \"a is greater\";\n} else {\n    cout << \"b is greater or equal\";\n}\n\nComparing Characters:\nchar c1 = 'A', c2 = 'B';\nc1 < c2;  // true (A comes before B in ASCII)\n'A' < 'B';  // true (65 < 66)\n\nCommon Mistakes:\n- Using = instead of ==\nif (x = 5) { ... }   // Assignment, not comparison!\nif (x == 5) { ... }  // Correct\n\n- Chaining comparisons (doesn't work as expected)\nif (1 < x < 10) { ... }  // WRONG! (1 < x) returns true/false, then (true < 10) is always true\nif (x > 1 && x < 10) { ... }  // Correct\n\n- Comparing floats for equality (use epsilon)\nif (abs(a - b) < 1e-9) { ... }  // Better than a == b",
    difficulty: "beginner",
    estimatedMinutes: 8,
    topic: "operators",
  },
  {
    id: "conditional-statements",
    subject: "cpp",
    title: "Conditional Statements",
    content: "Conditional statements let your program make decisions.\n\nif Statement:\nif (condition) {\n    // executes if condition is true\n}\n\nif-else:\nif (condition) {\n    // executes if true\n} else {\n    // executes if false\n}\n\nif-else if-else:\nif (score >= 90) {\n    grade = 'A';\n} else if (score >= 80) {\n    grade = 'B';\n} else if (score >= 70) {\n    grade = 'C';\n} else {\n    grade = 'F';\n}\n\nNested if:\nif (age >= 18) {\n    if (hasID) {\n        cout << \"Enter\";\n    } else {\n        cout << \"Need ID\";\n    }\n} else {\n    cout << \"Too young\";\n}\n\nShort Syntax (Single Statement):\nif (x > 0) cout << \"positive\";  // No braces needed for one line\n\nTernary Operator (Shortcut):\nstring result = (score >= 50) ? \"Pass\" : \"Fail\";\nEquivalent to:\nstring result;\nif (score >= 50) {\n    result = \"Pass\";\n} else {\n    result = \"Fail\";\n}\n\nBest Practices:\n- Always use braces (even for single lines)\n- Use else if for mutually exclusive conditions\n- Keep conditions simple and readable",
    difficulty: "beginner",
    estimatedMinutes: 10,
    topic: "conditionals",
  },
  {
    id: "logical-operators",
    subject: "cpp",
    title: "Logical Operators",
    content: "Logical operators combine multiple conditions.\n\nOperators:\n&&   Logical AND: both conditions must be true\n||   Logical OR: at least one condition must be true\n!    Logical NOT: inverts true/false\n\nExamples:\nint age = 25;\nbool hasID = true;\n\n// AND: both must be true\nif (age >= 18 && hasID) {\n    cout << \"Enter\";\n}\n\n// OR: at least one must be true\nif (age < 13 || age > 65) {\n    cout << \"Discount\";\n}\n\n// NOT: inverts\nif (!hasID) {\n    cout << \"Need ID\";\n}\n\nCombining Multiple Operators:\nif (age >= 18 && age <= 65 && hasID) {\n    cout << \"Standard entry\";\n}\n\nShort-Circuit Evaluation:\n- && stops at first false\n- || stops at first true\n\nExample:\nif (ptr != nullptr && ptr->value > 0) {\n    // If ptr is null, second condition is NOT evaluated\n    // This prevents null pointer dereference\n}\n\nCommon Mistakes:\n- Using & instead of &&\nif (x & 2)   // Bitwise AND (checks if bit 1 is set)\nif (x && 2)  // Logical AND (true if x is non-zero)\n\n- Confusing && and ||\n// \"At least 18 AND have ID\" (not OR)\nif (age >= 18 && hasID) { ... }",
    difficulty: "beginner",
    estimatedMinutes: 10,
    topic: "conditionals",
  },
  {
    id: "switch-statement",
    subject: "cpp",
    title: "switch",
    content: "The switch statement is an alternative to multiple if-else when comparing one value against many constants.\n\nBasic Syntax:\nint day = 3;\nswitch (day) {\n    case 1:\n        cout << \"Monday\";\n        break;\n    case 2:\n        cout << \"Tuesday\";\n        break;\n    case 3:\n        cout << \"Wednesday\";\n        break;\n    default:\n        cout << \"Other day\";\n        break;\n}\nOutput: Wednesday\n\nThe break Statement:\nWithout break, execution \"falls through\" to the next case:\nint x = 1;\nswitch (x) {\n    case 1: cout << \"one \";    // No break!\n    case 2: cout << \"two \";    // No break!\n    case 3: cout << \"three \";  // No break!\n}\nOutput: one two three\n\nFall-Through Can Be Useful:\nswitch (month) {\n    case 2:\n        days = 28;\n        break;\n    case 4: case 6: case 9: case 11:\n        days = 30;\n        break;\n    default:\n        days = 31;\n        break;\n}\n\nswitch vs if-else:\nUse switch when:\n- Comparing one variable against multiple constants\n- Cases are integer, char, or enum values\n\nUse if-else when:\n- Conditions are ranges (x > 10)\n- Conditions involve different variables\n- Floating-point comparisons",
    difficulty: "beginner",
    estimatedMinutes: 10,
    topic: "conditionals",
  },
  {
    id: "loops",
    subject: "cpp",
    title: "Loops",
    content: "Loops repeat a block of code multiple times.\n\nThree Types of Loops:\n1. for loop: when you know the number of iterations\n2. while loop: when you don't know iterations, check before each\n3. do-while loop: execute at least once, then check\n\nfor Loop:\nfor (int i = 0; i < 5; i++) {\n    cout << i << \" \";\n}\nOutput: 0 1 2 3 4\n\nwhile Loop:\nint i = 0;\nwhile (i < 5) {\n    cout << i << \" \";\n    i++;\n}\nOutput: 0 1 2 3 4\n\ndo-while Loop:\nint i = 0;\ndo {\n    cout << i << \" \";\n    i++;\n} while (i < 5);\nOutput: 0 1 2 3 4\n\nInfinite Loops:\nwhile (true) { ... }     // Runs forever (use break to exit)\nfor (;;) { ... }          // Same as while(true)\n\nWhen to Use Which:\n- for: counting, iterating over ranges\n- while: unknown iterations, sentinel values\n- do-while: menu systems, input validation",
    difficulty: "beginner",
    estimatedMinutes: 10,
    topic: "loops",
  },
  {
    id: "for-loop",
    subject: "cpp",
    title: "for Loop",
    content: "The for loop has three parts: initialization, condition, and update.\n\nSyntax:\nfor (init; condition; update) {\n    // body\n}\n\nExamples:\n// Count from 0 to 9\nfor (int i = 0; i < 10; i++) {\n    cout << i << \" \";\n}\nOutput: 0 1 2 3 4 5 6 7 8 9\n\n// Count backward\nfor (int i = 10; i > 0; i--) {\n    cout << i << \" \";\n}\nOutput: 10 9 8 7 6 5 4 3 2 1\n\n// Step by 2\nfor (int i = 0; i < 20; i += 2) {\n    cout << i << \" \";\n}\nOutput: 0 2 4 6 8 10 12 14 16 18\n\n// Nested loops (matrix)\nfor (int i = 0; i < 3; i++) {\n    for (int j = 0; j < 3; j++) {\n        cout << i*3 + j << \" \";\n    }\n    cout << endl;\n}\nOutput:\n0 1 2\n3 4 5\n6 7 8\n\n// Range-based for (C++11)\nint arr[] = {10, 20, 30};\nfor (int x : arr) {\n    cout << x << \" \";\n}\nOutput: 10 20 30\n\nCommon Mistakes:\n- Off-by-one: using <= instead of <\n- Forgetting to update: infinite loop\n- Modifying loop variable inside body",
    difficulty: "beginner",
    estimatedMinutes: 10,
    topic: "loops",
  },
  {
    id: "how-for-loop-executes",
    subject: "cpp",
    title: "How a for Loop Executes",
    content: "Understanding the execution order of a for loop:\n\nfor (int i = 0; i < 3; i++) {\n    cout << i << \" \";\n}\n\nStep-by-Step:\n1. Initialize: int i = 0 (runs once)\n2. Check: i < 3? (true: 0 < 3)\n3. Execute body: cout << 0 << \" \";\n4. Update: i++ (i becomes 1)\n5. Check: i < 3? (true: 1 < 3)\n6. Execute body: cout << 1 << \" \";\n7. Update: i++ (i becomes 2)\n8. Check: i < 3? (true: 2 < 3)\n9. Execute body: cout << 2 << \" \";\n10. Update: i++ (i becomes 3)\n11. Check: i < 3? (false: 3 < 3 is false)\n12. Loop ends\n\nExecution Order: init -> check -> body -> update -> check -> body -> update -> ...\n\nKey Insight:\nThe condition is checked BEFORE each iteration, including the first. If the condition is false initially, the body never executes.\n\nfor (int i = 10; i < 5; i++) {\n    cout << i;  // Never executes!\n}\n\nDo-While Executes at Least Once:\ndo {\n    cout << i;\n    i++;\n} while (i < 5);  // Body runs first, then checks",
    difficulty: "beginner",
    estimatedMinutes: 8,
    topic: "loops",
  },
  {
    id: "while-loop",
    subject: "cpp",
    title: "while Loop",
    content: "The while loop repeats as long as a condition is true.\n\nSyntax:\nwhile (condition) {\n    // body\n}\n\nExamples:\n// Count from 0 to 4\nint i = 0;\nwhile (i < 5) {\n    cout << i << \" \";\n    i++;\n}\nOutput: 0 1 2 3 4\n\n// Sum until user enters 0\nint sum = 0, num;\ncout << \"Enter numbers (0 to stop): \";\ncin >> num;\nwhile (num != 0) {\n    sum += num;\n    cin >> num;\n}\ncout << \"Sum: \" << sum;\n\n// Input validation\nint age;\ncout << \"Enter age (1-120): \";\ncin >> age;\nwhile (age < 1 || age > 120) {\n    cout << \"Invalid. Try again: \";\n    cin >> age;\n}\n\nwhile vs for:\n- Use for when you know the number of iterations\n- Use while when the number of iterations is unknown\n- Both can be used interchangeably\n\nCommon Mistakes:\n- Forgetting to update the variable\nint i = 0;\nwhile (i < 5) {\n    cout << i;\n    // Forgot i++ -> infinite loop!\n}\n\n- Infinite loop with condition always true\nwhile (true) { ... }  // Use break to exit",
    difficulty: "beginner",
    estimatedMinutes: 10,
    topic: "loops",
  },
  {
    id: "do-while-loop",
    subject: "cpp",
    title: "do-while",
    content: "The do-while loop executes the body first, then checks the condition.\n\nSyntax:\ndo {\n    // body\n} while (condition);  // Note the semicolon!\n\nKey Difference:\n- while: checks condition BEFORE execution\n- do-while: checks condition AFTER execution (guaranteed at least one execution)\n\nExamples:\n// Menu system\nint choice;\ndo {\n    cout << \"\\n=== Menu ===\" << endl;\n    cout << \"1. Start\" << endl;\n    cout << \"2. Settings\" << endl;\n    cout << \"3. Quit\" << endl;\n    cout << \"Choice: \";\n    cin >> choice;\n\n    switch (choice) {\n        case 1: cout << \"Starting...\"; break;\n        case 2: cout << \"Settings...\"; break;\n        case 3: cout << \"Goodbye!\"; break;\n        default: cout << \"Invalid choice\";\n    }\n} while (choice != 3);\n\n// Input validation\nint num;\ndo {\n    cout << \"Enter a positive number: \";\n    cin >> num;\n} while (num <= 0);\n\n// Always executes at least once\nint x = 100;\ndo {\n    cout << x;  // Prints 100\n} while (x < 50);  // Condition is false, but body ran once\n\nWhen to Use do-while:\n- Menu systems (show menu at least once)\n- Input validation (prompt at least once)\n- Game loops (run at least one frame)",
    difficulty: "beginner",
    estimatedMinutes: 8,
    topic: "loops",
  },
  {
    id: "break-and-continue",
    subject: "cpp",
    title: "break and continue",
    content: "break and continue control loop execution.\n\nbreak — Exit the Loop Immediately:\nfor (int i = 0; i < 100; i++) {\n    if (i == 5) {\n        break;  // Exit when i reaches 5\n    }\n    cout << i << \" \";\n}\nOutput: 0 1 2 3 4\n\ncontinue — Skip to Next Iteration:\nfor (int i = 0; i < 10; i++) {\n    if (i % 2 == 0) {\n        continue;  // Skip even numbers\n    }\n    cout << i << \" \";\n}\nOutput: 1 3 5 7 9\n\nbreak in Nested Loops:\nfor (int i = 0; i < 3; i++) {\n    for (int j = 0; j < 3; j++) {\n        if (j == 1) break;  // Only exits inner loop\n        cout << i << \",\" << j << \" \";\n    }\n}\nOutput: 0,0 1,0 2,0\n\ncontinue in Nested Loops:\nfor (int i = 0; i < 3; i++) {\n    for (int j = 0; j < 3; j++) {\n        if (j == 1) continue;  // Skips only inner iteration\n        cout << i << \",\" << j << \" \";\n    }\n}\nOutput: 0,0 0,2 1,0 1,2 2,0 2,2\n\nbreak in switch:\nswitch (x) {\n    case 1: cout << \"one\"; break;  // Prevents fall-through\n    case 2: cout << \"two\"; break;\n}\n\nBest Practice:\n- Use break to exit early (when you find what you need)\n- Use continue to skip iterations cleanly\n- Avoid excessive break/continue (hard to read)\n- Prefer returning from a function over complex break logic",
    difficulty: "beginner",
    estimatedMinutes: 10,
    topic: "loops",
  },
  {
    id: "functions",
    subject: "cpp",
    title: "Functions",
    content: "Functions are reusable blocks of code that perform a specific task.\n\nWhy Use Functions?\n- Avoid code duplication\n- Make code readable and organized\n- Easier to test and debug\n- Break complex problems into smaller pieces\n\nFunction Syntax:\nreturn_type function_name(parameters) {\n    // body\n    return value;  // if not void\n}\n\nExamples:\nvoid greet() {\n    cout << \"Hello!\" << endl;\n}\n\nint add(int a, int b) {\n    return a + b;\n}\n\ndouble calculateArea(double width, double height) {\n    return width * height;\n}\n\nCalling Functions:\ngreet();                     // Call greet\nint sum = add(3, 5);        // sum = 8\ndouble area = calculateArea(4.0, 5.0);  // area = 20.0\n\nFunction Declaration vs Definition:\n// Declaration (prototype) — tells compiler about function\nint add(int a, int b);  // No body\n\n// Definition — actual implementation\nint add(int a, int b) {\n    return a + b;\n}\n\nPrototypes are placed before main(), definitions after main().\n\nScope:\nint x = 10;  // Global variable\nvoid foo() {\n    int x = 20;  // Local variable (shadows global)\n    cout << x;   // Prints 20\n}",
    difficulty: "beginner",
    estimatedMinutes: 12,
    topic: "functions",
  },
  {
    id: "function-parameters",
    subject: "cpp",
    title: "Function Parameters",
    content: "Parameters are the values passed to a function.\n\nPass by Value (Default):\nvoid increment(int x) {\n    x++;  // Only modifies local copy\n}\n\nint main() {\n    int a = 5;\n    increment(a);\n    cout << a;  // Still 5 (original unchanged)\n}\n\nPass by Reference (Use &):\nvoid increment(int& x) {\n    x++;  // Modifies original variable\n}\n\nint main() {\n    int a = 5;\n    increment(a);\n    cout << a;  // Now 6 (original modified)\n}\n\nPass by Const Reference (Read-Only, Efficient):\nvoid print(const string& s) {\n    cout << s;\n    // s = \"new\";  // Error: const prevents modification\n}\n\nUse const& for:\n- Large objects (avoids copying)\n- When you don't need to modify the parameter\n- String parameters (string copy is expensive)\n\nDefault Parameters:\nvoid greet(string name = \"Guest\") {\n    cout << \"Hello, \" << name;\n}\n\ngreet(\"Alice\");  // Hello, Alice\ngreet();          // Hello, Guest\n\nRule: Default parameters must be at the end of the parameter list.\nvoid foo(int a = 1, int b);  // Error!\nvoid foo(int a, int b = 2);  // OK",
    difficulty: "beginner",
    estimatedMinutes: 10,
    topic: "functions",
  },
  {
    id: "return-values",
    subject: "cpp",
    title: "Return Values",
    content: "Functions can return a value using the return statement.\n\nReturning Different Types:\nint add(int a, int b) { return a + b; }\ndouble divide(int a, int b) { return static_cast<double>(a) / b; }\nbool isPositive(int x) { return x > 0; }\nchar getGrade(int score) {\n    if (score >= 90) return 'A';\n    if (score >= 80) return 'B';\n    return 'F';\n}\n\nReturning Multiple Values:\n// Option 1: Use reference parameters\nvoid getMinMax(int a, int b, int& min, int& max) {\n    min = (a < b) ? a : b;\n    max = (a > b) ? a : b;\n}\n\n// Option 2: Use struct\nstruct Result { int min; int max; };\nResult getMinMax(int a, int b) {\n    return { min(a), b) };\n}\n\nEarly Return:\nint findIndex(int arr[], int n, int target) {\n    for (int i = 0; i < n; i++) {\n        if (arr[i] == target) return i;  // Found it!\n    }\n    return -1;  // Not found\n}\n\nvoid process(int x) {\n    if (x < 0) return;  // Exit early if invalid\n    // ... continue processing\n}\n\nCommon Mistakes:\n- Forgetting to return a value (undefined behavior)\n- Returning reference to local variable (dangling reference)\n- Returning different types in different paths",
    difficulty: "beginner",
    estimatedMinutes: 10,
    topic: "functions",
  },
  {
    id: "function-structure",
    subject: "cpp",
    title: "Function Structure",
    content: "Anatomy of a well-structured function:\n\n// Function signature (return type + name + parameters)\ndouble calculateAverage(const vector<int>& numbers) {\n    // Guard clause (handle edge cases)\n    if (numbers.empty()) {\n        return 0.0;\n    }\n\n    // Main logic\n    double sum = 0;\n    for (int num : numbers) {\n        sum += num;\n    }\n\n    // Return result\n    return sum / numbers.size();\n}\n\nFunction Organization:\n1. Guard clause: handle edge cases first\n2. Main logic: the core algorithm\n3. Return: the result\n\nSingle Responsibility Principle:\nEach function should do ONE thing well.\n\n// Bad: does too many things\nvoid processStudent(int id, string name, double gpa) {\n    // validates, calculates, prints, saves to file...\n}\n\n// Good: each function does one thing\nbool validateStudent(int id, string name);\ndouble calculateHonors(double gpa);\nvoid displayStudent(int id, string name, double gpa);\nvoid saveStudent(int id, string name, double gpa);\n\nFunction Length Guidelines:\n- 1-20 lines: ideal\n- 20-50 lines: acceptable\n- 50+ lines: consider splitting\n\nNaming Functions:\n- Use verbs: calculateArea, printReport, getMax\n- Be descriptive: calculateStudentAverage (not calc)\n- Follow conventions: camelCase or snake_case (be consistent)",
    difficulty: "beginner",
    estimatedMinutes: 10,
    topic: "functions",
  },
  {
    id: "arrays",
    subject: "cpp",
    title: "Arrays",
    content: "An array is a collection of elements of the same type stored in contiguous memory.\n\nDeclaring Arrays:\nint scores[5];           // 5 integers (uninitialized)\nint nums[5] = {1,2,3,4,5};  // Initialized\nint zeros[5] = {};       // All zeros\nint partial[5] = {1,2};  // {1,2,0,0,0}\n\nAccessing Elements:\nint arr[5] = {10, 20, 30, 40, 50};\narr[0];   // 10 (first element)\narr[4];   // 50 (last element)\narr[5];   // OUT OF BOUNDS! Undefined behavior\n\nArray Size:\nint arr[5] = {1, 2, 3, 4, 5};\nsizeof(arr);       // 20 bytes (5 * 4 bytes per int)\nsizeof(arr[0]);    // 4 bytes (size of one int)\n\n// Modern C++ (preferred)\nint size = std::size(arr);  // 5\n\n// Or compute\nint size = sizeof(arr) / sizeof(arr[0]);  // 5\n\nModifying Elements:\nint arr[5] = {1, 2, 3, 4, 5};\narr[0] = 100;   // {100, 2, 3, 4, 5}\narr[2] = 99;    // {100, 2, 99, 4, 5}\n\nCommon Mistakes:\n- Array index out of bounds (no runtime check!)\n- Using variable index in C-style array: arr[i] is OK, but arr[n] where n is not constant is fine in C++\n- Forgetting arrays are 0-indexed\n- Comparing arrays: arr1 == arr2 doesn't work (compares addresses)",
    difficulty: "beginner",
    estimatedMinutes: 10,
    topic: "arrays-strings",
  },
  {
    id: "array-indexing",
    subject: "cpp",
    title: "Array Indexing",
    content: "Arrays use 0-based indexing: the first element is at index 0.\n\nint arr[5] = {10, 20, 30, 40, 50};\n\nIndex:    0    1    2    3    4\nElement: 10   20   30   40   50\n\nAccessing by Index:\narr[0] = 10  (first)\narr[1] = 20\narr[2] = 30\narr[3] = 40\narr[4] = 50  (last)\n\nOff-by-One Error:\nfor (int i = 0; i <= 5; i++) {  // WRONG: i <= 5 goes out of bounds\n    cout << arr[i];\n}\n\nfor (int i = 0; i < 5; i++) {  // CORRECT: i < 5 stays in bounds\n    cout << arr[i];\n}\n\nThe Golden Rule:\nFor array of size N, valid indices are 0 to N-1.\nArray of size 5: valid indices are 0, 1, 2, 3, 4\n\nArray Traversal:\nint arr[5] = {10, 20, 30, 40, 50};\n\n// Method 1: Index-based\nfor (int i = 0; i < 5; i++) {\n    cout << arr[i] << \" \";\n}\n\n// Method 2: Range-based (C++11)\nfor (int x : arr) {\n    cout << x << \" \";\n}\n\n// Method 3: Using pointers\nfor (int* p = arr; p < arr + 5; p++) {\n    cout << *p << \" \";\n}\n\nCommon Mistakes:\n- Using <= instead of < in loop condition\n- Using unsigned types for loop counters (underflow risk)\n- Accessing arr[-1] (wraps around to huge index)",
    difficulty: "beginner",
    estimatedMinutes: 10,
    topic: "arrays-strings",
  },
  {
    id: "arrays-plus-loops",
    subject: "cpp",
    title: "Arrays + Loops",
    content: "Arrays and loops work together for most array operations.\n\nSum of Array:\nint arr[5] = {10, 20, 30, 40, 50};\nint sum = 0;\nfor (int i = 0; i < 5; i++) {\n    sum += arr[i];\n}\ncout << \"Sum: \" << sum;  // 150\n\nFind Maximum:\nint arr[5] = {3, 7, 2, 9, 5};\nint maxVal = arr[0];\nfor (int i = 1; i < 5; i++) {\n    if (arr[i] > maxVal) {\n        maxVal = arr[i];\n    }\n}\ncout << \"Max: \" << maxVal;  // 9\n\nCount Occurrences:\nint arr[7] = {1, 2, 3, 2, 4, 2, 5};\nint count = 0;\nfor (int i = 0; i < 7; i++) {\n    if (arr[i] == 2) count++;\n}\ncout << \"2 appears \" << count << \" times\";  // 3\n\nReverse Array:\nint arr[5] = {1, 2, 3, 4, 5};\nfor (int i = 0; i < 5 / 2; i++) {\n    swap(arr[i], arr[4 - i]);\n}\n// arr is now {5, 4, 3, 2, 1}\n\nLinear Search:\nint arr[5] = {10, 20, 30, 40, 50};\nint target = 30;\nint index = -1;\nfor (int i = 0; i < 5; i++) {\n    if (arr[i] == target) {\n        index = i;\n        break;\n    }\n}\ncout << \"Found at index: \" << index;  // 2",
    difficulty: "beginner",
    estimatedMinutes: 10,
    topic: "arrays-strings",
  },
  {
    id: "strings",
    subject: "cpp",
    title: "Strings",
    content: "std::string is a class that handles text in C++.\n\n#include <string>\n\nDeclaring Strings:\nstring s1 = \"Hello\";\nstring s2(\"World\");\nstring s3 = s1 + \" \" + s2;  // \"Hello World\"\nstring s4(5, 'a');            // \"aaaaa\"\n\nCommon Operations:\nstring s = \"Hello\";\n\ns.length();       // 5 (number of characters)\ns.size();         // 5 (same as length())\ns.empty();        // false\ns[0];             // 'H' (first character)\ns.at(0);          // 'H' (bounds-checked)\ns.front();        // 'H'\ns.back();         // 'o' (last character)\n\nConcatenation:\nstring first = \"Hello\";\nstring second = \" World\";\nstring result = first + second;  // \"Hello World\"\n\nfirst += \"!\";  // \"Hello!\" (append)\nfirst.append(\"?\");  // \"Hello!?\" (append)\n\nSubstring:\nstring s = \"Hello World\";\ns.substr(0, 5);     // \"Hello\" (start, length)\ns.substr(6);        // \"World\" (from index 6 to end)\n\nFind:\nstring s = \"Hello World\";\ns.find(\"World\");    // 6 (index of first occurrence)\ns.find(\"xyz\");      // string::npos (not found)\n\nComparison:\nstring a = \"apple\";\nstring b = \"banana\";\nif (a < b) { ... }  // Lexicographic comparison ('a' < 'b')\n\nString Input:\nstring name;\ncin >> name;           // Reads one word\ncin >> ws;             // Discard whitespace\ngetline(cin, name);    // Reads entire line",
    difficulty: "beginner",
    estimatedMinutes: 12,
    topic: "arrays-strings",
  },
  {
    id: "getline",
    subject: "cpp",
    title: "getline()",
    content: "getline() reads an entire line of input, including spaces.\n\nWhy getline()?\ncin >> name;  // Reads only up to the first space\n// Input: \"John Smith\"\n// name gets \"John\" (not \"John Smith\")\n\nUsing getline:\nstring fullName;\ncout << \"Enter name: \";\ngetline(cin, fullName);\n// Input: \"John Smith\"\n// fullName gets \"John Smith\"\n\ngetline with Delimiter:\nstring line;\ngetline(cin, line, ',');  // Read until comma\n// Input: \"apple,banana,cherry\"\n// line gets \"apple\"\n\nMixing cin >> and getline:\nint age;\nstring name;\ncout << \"Age: \";\ncin >> age;\ncout << \"Name: \";\ngetline(cin, name);  // PROBLEM: reads the leftover newline!\n\n// Fix: clear the newline buffer\ncin >> age;\ncin.ignore();  // Discard the newline\ngetline(cin, name);  // Now works correctly\n\nReading Multiple Lines:\nstring line;\nwhile (getline(cin, line)) {\n    if (line.empty()) break;  // Stop on empty line\n    cout << \"Read: \" << line << endl;\n}\n\nExample: Read a Sentence and Count Words:\nstring sentence;\ngetline(cin, sentence);\n\nint wordCount = 0;\nbool inWord = false;\nfor (char c : sentence) {\n    if (c == ' ') {\n        inWord = false;\n    } else if (!inWord) {\n        wordCount++;\n        inWord = true;\n    }\n}\ncout << \"Words: \" << wordCount;",
    difficulty: "beginner",
    estimatedMinutes: 10,
    topic: "arrays-strings",
  },
  {
    id: "pointers",
    subject: "cpp",
    title: "Pointers",
    content: "A pointer stores the memory address of another variable.\n\nDeclaring Pointers:\nint x = 10;\nint* p = &x;  // p stores the address of x\n\nThe & Operator (Address-Of):\nint x = 10;\nint* p = &x;  // p = 0x7ffd5e8a3c4c (some address)\n\nThe * Operator (Dereference):\ncout << *p;    // 10 (go to address, read value)\n*p = 20;       // x is now 20\n\nMemory Visualization:\nint x = 10;    // Variable x, value 10, address 0x100\nint* p = &x;   // Pointer p, value 0x100, address 0x200\n\nMemory:\nAddress  Value\n0x100    10       (x)\n0x200    0x100    (p)\n\nNull Pointer:\nint* p = nullptr;  // Points to nothing\nif (p != nullptr) {\n    cout << *p;  // Only dereference non-null pointers\n}\n\nPointer Arithmetic:\nint arr[5] = {10, 20, 30, 40, 50};\nint* p = arr;      // p points to arr[0]\n*(p + 1);          // 20 (arr[1])\n*(p + 2);          // 30 (arr[2])\np++;                // p now points to arr[1]\n\nCommon Mistakes:\n- Dereferencing null pointer: *nullptr (crash)\n- Dangling pointer: p points to freed memory\n- Uninitialized pointer: int* p; *p = 5; (wild pointer)",
    difficulty: "intermediate",
    estimatedMinutes: 12,
    topic: "pointers",
  },
  {
    id: "pointer-example",
    subject: "cpp",
    title: "Pointer Example",
    content: "Practical example using pointers:\n\n#include <iostream>\nusing namespace std;\n\n// Swap using pointers\nvoid swap(int* a, int* b) {\n    int temp = *a;\n    *a = *b;\n    *b = temp;\n}\n\n// Swap using references (preferred)\nvoid swapRef(int& a, int& b) {\n    int temp = a;\n    a = b;\n    b = temp;\n}\n\nint main() {\n    int x = 5, y = 10;\n\n    cout << \"Before: x=\" << x << \" y=\" << y << endl;\n\n    swap(&x, &y);  // Pass addresses\n    cout << \"After swap: x=\" << x << \" y=\" << y << endl;\n\n    // Or using references (cleaner)\n    swapRef(x, y);\n    cout << \"After swapRef: x=\" << x << \" y=\" << y << endl;\n}\nOutput:\nBefore: x=5 y=10\nAfter swap: x=10 y=5\nAfter swapRef: x=5 y=10\n\nDynamic Array with Pointers:\nint n = 5;\nint* arr = new int[n];  // Allocate on heap\nfor (int i = 0; i < n; i++) {\n    arr[i] = i * 10;\n}\nfor (int i = 0; i < n; i++) {\n    cout << arr[i] << \" \";\n}\ndelete[] arr;  // Free memory\narr = nullptr;\n\nKey Takeaways:\n- Use pointers when you need to modify the original variable\n- Use references when null isn't meaningful (cleaner syntax)\n- Always initialize pointers before use\n- Always free dynamically allocated memory",
    difficulty: "intermediate",
    estimatedMinutes: 10,
    topic: "pointers",
  },
  {
    id: "references",
    subject: "cpp",
    title: "References",
    content: "A reference is an alias for an existing variable.\n\nDeclaring References:\nint x = 10;\nint& ref = x;  // ref is another name for x\nref = 20;      // x is now 20\n\nReference Rules:\n- Must be initialized when declared\n- Cannot be null\n- Cannot be reassigned to refer to another variable\n\nReference vs Pointer:\nint x = 10, y = 20;\n\n// Pointer\nint* ptr = &x;  // OK: pointer to x\nptr = &y;       // OK: reassign to point to y\n*ptr = 30;      // y is now 30\n\n// Reference\nint& ref = x;   // OK: ref aliases x\nref = 30;       // x is now 30 (not reassignment!)\n// int& ref2 = y;  // Error: cannot reassign reference\n\nPass by Reference (Function Parameters):\nvoid increment(int& x) {\n    x++;  // Modifies original variable\n}\n\nint main() {\n    int a = 5;\n    increment(a);  // a is now 6\n}\n\nUse Cases:\n1. Function parameters (modify original, avoid copying)\n2. Range-based for loops (avoid copying)\n3. Operator overloading\n\nWhen to Use References vs Pointers:\nReference: when null isn't meaningful, when you need an alias\nPointer: when null is meaningful, when you need to reassign",
    difficulty: "intermediate",
    estimatedMinutes: 10,
    topic: "pointers",
  },
  {
    id: "structures",
    subject: "cpp",
    title: "Structures",
    content: "A structure (struct) groups related variables under one name.\n\nDeclaring a Structure:\nstruct Student {\n    string name;\n    int age;\n    double gpa;\n};\n\nUsing Structures:\nStudent s1;\ns1.name = \"Alice\";\ns1.age = 20;\ns1.gpa = 3.8;\n\n// Or initialize directly\nStudent s2 = {\"Bob\", 22, 3.5};\n\n// Or with braces (C++11)\nStudent s3{\"Charlie\", 21, 3.9};\n\nPrinting Structures:\nvoid printStudent(const Student& s) {\n    cout << \"Name: \" << s.name << endl;\n    cout << \"Age: \" << s.age << endl;\n    cout << \"GPA: \" << s.gpa << endl;\n}\n\nArray of Structures:\nStudent class_[3] = {\n    {\"Alice\", 20, 3.8},\n    {\"Bob\", 22, 3.5},\n    {\"Charlie\", 21, 3.9}\n};\n\nfor (int i = 0; i < 3; i++) {\n    printStudent(class_[i]);\n}\n\nStructures vs Separate Variables:\n// Bad: separate variables\nstring name1, name2, name3;\nint age1, age2, age3;\ndouble gpa1, gpa2, gpa3;\n\n// Good: array of structures\nstruct Student { string name; int age; double gpa; };\nStudent students[3];\n\nStructures are the foundation of OOP — classes are just structs with functions.",
    difficulty: "beginner",
    estimatedMinutes: 10,
    topic: "structures",
  },
  {
    id: "intro-to-oop",
    subject: "cpp",
    title: "Introduction to OOP",
    content: "Object-Oriented Programming (OOP) organizes code around objects that combine data and behavior.\n\nFour Pillars of OOP:\n1. Encapsulation: bundling data and methods, hiding internal details\n2. Inheritance: creating new classes from existing ones\n3. Polymorphism: same interface, different implementations\n4. Abstraction: exposing only essential features\n\nWhy OOP?\n- Models real-world concepts naturally\n- Promotes code reuse\n- Makes large programs manageable\n- Enables polymorphic behavior\n\nKey Concepts:\n- Class: A blueprint (template) for creating objects\n- Object: An instance of a class\n- Member variables: Data stored in the object\n- Member functions: Operations the object can perform\n\nExample: Car Analogy\n- Class: Car (the blueprint)\n- Objects: My car, your car, that car (instances)\n- Attributes: color, speed, fuel (member variables)\n- Behaviors: accelerate, brake, turn (member functions)\n\nBefore OOP:\nstruct Student { string name; int age; };\nvoid printStudent(Student s) { ... }\n\nAfter OOP:\nclass Student {\n    string name;\n    int age;\npublic:\n    void print() { ... }\n};",
    difficulty: "intermediate",
    estimatedMinutes: 10,
    topic: "oops",
  },
  {
    id: "classes",
    subject: "cpp",
    title: "Classes",
    content: "A class defines the structure and behavior of objects.\n\nclass Car {\nprivate:\n    string brand;\n    int speed;\n\npublic:\n    // Constructor\n    Car(string b, int s) : brand(b), speed(s) {}\n\n    // Member functions\n    void accelerate(int amount) {\n        speed += amount;\n    }\n\n    void brake(int amount) {\n        speed -= amount;\n        if (speed < 0) speed = 0;\n    }\n\n    int getSpeed() const {\n        return speed;\n    }\n\n    string getBrand() const {\n        return brand;\n    }\n};\n\nUsing the Class:\nCar myCar(\"Toyota\", 0);\nmyCar.accelerate(60);\ncout << myCar.getBrand() << \" speed: \" << myCar.getSpeed();\n// Toyota speed: 60\n\nAccess Specifiers:\n- private: accessible only within the class (default)\n- public: accessible from anywhere\n- protected: accessible within class and derived classes\n\nMember Initialization List:\nCar(string b, int s) : brand(b), speed(s) { }\n// More efficient than assignment in the body\n\nconst Member Functions:\nint getSpeed() const { return speed; }\n// Promises not to modify the object\n\nCommon Mistakes:\n- Forgetting access specifiers (everything is private by default)\n- Not making getters const\n- Defining member functions outside class without scope resolution",
    difficulty: "intermediate",
    estimatedMinutes: 12,
    topic: "oops",
  },
  {
    id: "class-vs-object",
    subject: "cpp",
    title: "Class vs Object",
    content: "Class = Blueprint\nObject = Instance\n\nAnalogy:\n- Class: Cookie cutter (defines the shape)\n- Object: Cookie (actual thing created from the cutter)\n\nYou can make many cookies from one cutter.\nYou can make many objects from one class.\n\nExample:\nclass Student {\n    string name;\n    int age;\npublic:\n    Student(string n, int a) : name(n), age(a) {}\n    void display() { cout << name << \", \" << age; }\n};\n\n// Objects (instances)\nStudent s1(\"Alice\", 20);  // Object 1\nStudent s2(\"Bob\", 22);    // Object 2\nStudent s3(\"Charlie\", 21); // Object 3\n\nEach object has its own copy of member variables:\ns1.name = \"Alice\", s1.age = 20\ns2.name = \"Bob\", s2.age = 22\ns3.name = \"Charlie\", s3.age = 21\n\nMemory Layout:\nEach object occupies its own memory:\n- s1: [name=\"Alice\", age=20]\n- s2: [name=\"Bob\", age=22]\n- s3: [name=\"Charlie\", age=21]\n\nKey Differences:\nClass:\n- Defines structure and behavior\n- Takes no memory (just a blueprint)\n- Declared once\n\nObject:\n- Takes memory (stores actual data)\n- Created from a class\n- Multiple objects from one class",
    difficulty: "intermediate",
    estimatedMinutes: 10,
    topic: "oops",
  },
  {
    id: "constructors",
    subject: "cpp",
    title: "Constructors",
    content: "A constructor is a special function called when an object is created.\n\nTypes of Constructors:\n\n1. Default Constructor (no parameters):\nclass Point {\n    int x, y;\npublic:\n    Point() : x(0), y(0) {}  // Default constructor\n};\nPoint p;  // p.x = 0, p.y = 0\n\n2. Parameterized Constructor:\nclass Point {\n    int x, y;\npublic:\n    Point(int x, int y) : x(x), y(y) {}\n};\nPoint p(5, 10);  // p.x = 5, p.y = 10\n\n3. Copy Constructor:\nclass Point {\n    int x, y;\npublic:\n    Point(const Point& other) : x(other.x), y(other.y) {}\n};\nPoint p1(5, 10);\nPoint p2(p1);  // p2 is a copy of p1\n\nInitializer Lists (Preferred):\n// Member initializer list (before constructor body)\nPoint(int x, int y) : x(x), y(y) {\n    // Constructor body\n}\n\n// More efficient than:\nPoint(int x, int y) {\n    this->x = x;  // Assignment (less efficient)\n    this->y = y;\n}\n\nConstructor Rules:\n- Same name as the class\n- No return type (not even void)\n- Called automatically when object is created\n- Can be overloaded (multiple constructors)\n\nWhen No Constructor Is Defined:\n- C++ provides a default constructor (does nothing)\n- C++ provides a copy constructor (shallow copy)\n\nCommon Mistakes:\n- Defining a parameterized constructor without a default constructor\n- Forgetting to initialize all members",
    difficulty: "intermediate",
    estimatedMinutes: 12,
    topic: "oops",
  },
  {
    id: "encapsulation",
    subject: "cpp",
    title: "Encapsulation",
    content: "Encapsulation bundles data and methods together, hiding internal details.\n\nWhat It Does:\n- Data hiding: private members can't be accessed from outside\n- Controlled access: public methods provide safe interfaces\n- Flexibility: internal implementation can change without affecting users\n\nExample:\nclass BankAccount {\nprivate:\n    string owner;\n    double balance;\n\npublic:\n    BankAccount(string owner, double initial)\n        : owner(owner), balance(initial) {}\n\n    // Public interface (safe access)\n    void deposit(double amount) {\n        if (amount > 0) balance += amount;\n    }\n\n    bool withdraw(double amount) {\n        if (amount > 0 && amount <= balance) {\n            balance -= amount;\n            return true;\n        }\n        return false;\n    }\n\n    double getBalance() const { return balance; }\n    string getOwner() const { return owner; }\n};\n\n// User of the class\nBankAccount acc(\"Alice\", 1000);\nacc.deposit(500);     // OK\nacc.withdraw(200);    // OK\n// acc.balance = 1000000;  // Error! balance is private\n\nBenefits:\n1. Prevents invalid states (negative balance)\n2. Internal changes don't break external code\n3. Easier to debug (access through controlled methods)\n4. Enables validation at access points\n\nGetters and Setters:\nclass Student {\nprivate:\n    int age;\npublic:\n    void setAge(int a) {\n        if (a >= 0 && a <= 150) age = a;\n    }\n    int getAge() const { return age; }\n};",
    difficulty: "intermediate",
    estimatedMinutes: 10,
    topic: "oops",
  },
  {
    id: "inheritance",
    subject: "cpp",
    title: "Inheritance",
    content: "Inheritance lets a new class reuse code from an existing class.\n\nBase Class (Parent):\nclass Animal {\npublic:\n    void eat() { cout << \"Eating...\"; }\n    void sleep() { cout << \"Sleeping...\"; }\n};\n\nDerived Class (Child):\nclass Dog : public Animal {\npublic:\n    void bark() { cout << \"Woof!\"; }\n};\n\nUsing Inheritance:\nDog dog;\ndog.eat();     // Inherited from Animal\ndog.sleep();   // Inherited from Animal\ndog.bark();    // Own method\n\nAccess Specifiers in Inheritance:\n- public: most common, preserves access levels\n- protected: members become protected in derived class\n- private: members become private in derived class (rarely used)\n\npublic Inheritance:\nBase class    In derived class\npublic        public\nprotected     protected\nprivate       inaccessible\n\nTypes of Inheritance:\n1. Single: A -> B\n2. Multiple: A, B -> C\n3. Multilevel: A -> B -> C\n4. Hierarchical: A -> B, A -> C\n\nWhen to Use Inheritance:\n- IS-A relationship: Dog IS-A Animal\n- Code reuse: common behavior in base class\n- Polymorphism: base class pointer to derived object\n\nWhen NOT to Use:\n- HAS-A relationship (use composition instead)\n- Code reuse only (prefer delegation)",
    difficulty: "intermediate",
    estimatedMinutes: 12,
    topic: "oops",
  },
  {
    id: "polymorphism",
    subject: "cpp",
    title: "Polymorphism",
    content: "Polymorphism means \"many forms\" — same interface, different implementations.\n\nTwo Types:\n1. Compile-time (static): function overloading, templates\n2. Run-time (dynamic): virtual functions\n\nFunction Overloading:\nint add(int a, int b) { return a + b; }\ndouble add(double a, double b) { return a + b; }\nstring add(string a, string b) { return a + b; }\n// Same name, different parameter types\n\nVirtual Functions (Run-Time Polymorphism):\nclass Shape {\npublic:\n    virtual double area() const = 0;  // Pure virtual\n    virtual ~Shape() {}                // Virtual destructor\n};\n\nclass Circle : public Shape {\n    double radius;\npublic:\n    Circle(double r) : radius(r) {}\n    double area() const override { return 3.14159 * radius * radius; }\n};\n\nclass Rectangle : public Shape {\n    double width, height;\npublic:\n    Rectangle(double w, double h) : width(w), height(h) {}\n    double area() const override { return width * height; }\n};\n\nUsing Polymorphism:\nShape* shapes[] = { new Circle(5), new Rectangle(4, 6) };\nfor (Shape* s : shapes) {\n    cout << s->area() << endl;  // Calls correct area() at runtime\n}\n// Output: 78.54, 24\n\nKey Keywords:\n- virtual: enables run-time dispatch\n- override: explicitly marks overriding functions (C++11)\n- = 0: pure virtual (abstract class, cannot be instantiated)",
    difficulty: "advanced",
    estimatedMinutes: 15,
    topic: "oops",
  },
  {
    id: "exception-handling",
    subject: "cpp",
    title: "Exception Handling",
    content: "Exception handling manages runtime errors gracefully.\n\nBasic Syntax:\ntry {\n    // Code that might throw\n    int result = 10 / 0;  // Throws exception\n} catch (const exception& e) {\n    // Handle the error\n    cout << \"Error: \" << e.what();\n} catch (...) {\n    // Catch any other exception\n    cout << \"Unknown error\";\n}\n\nThrowing Exceptions:\ndouble divide(int a, int b) {\n    if (b == 0) {\n        throw runtime_error(\"Division by zero\");\n    }\n    return static_cast<double>(a) / b;\n}\n\nCustom Exceptions:\nclass InsufficientFunds : public exception {\n    double amount;\npublic:\n    InsufficientFunds(double a) : amount(a) {}\n    const char* what() const noexcept override {\n        return \"Insufficient funds\";\n    }\n    double getAmount() const { return amount; }\n};\n\nvoid withdraw(double balance, double amount) {\n    if (amount > balance) {\n        throw InsufficientFunds(amount - balance);\n    }\n}\n\nException Safety:\n- Use RAII (Resource Acquisition Is Initialization)\n- Smart pointers handle cleanup automatically\n- Destructors are called during stack unwinding\n\nWhen to Use Exceptions:\n- Exceptional conditions (file not found, network error)\n- Library boundaries\n- When error codes would be cumbersome\n\nWhen NOT to Use:\n- Normal control flow (use return codes)\n- Performance-critical code (exceptions have overhead)\n- Simple functions with obvious error conditions",
    difficulty: "advanced",
    estimatedMinutes: 12,
    topic: "oops",
  },
  {
    id: "file-handling",
    subject: "cpp",
    title: "File Handling",
    content: "File handling lets you read from and write to files.\n\n#include <fstream>\n#include <iostream>\nusing namespace std;\n\nWriting to a File:\nofstream outFile(\"output.txt\");\nif (outFile.is_open()) {\n    outFile << \"Hello, World!\" << endl;\n    outFile << 42 << endl;\n    outFile.close();\n}\n\nReading from a File:\nifstream inFile(\"input.txt\");\nif (inFile.is_open()) {\n    string line;\n    while (getline(inFile, line)) {\n        cout << line << endl;\n    }\n    inFile.close();\n}\n\nReading Numbers:\nifstream inFile(\"numbers.txt\");\nint num;\nwhile (inFile >> num) {\n    cout << num << \" \";\n}\n\nFile Modes:\nofstream outFile(\"file.txt\", ios::app);  // Append mode\nofstream outFile(\"file.txt\", ios::trunc); // Truncate (default)\nifstream inFile(\"file.txt\", ios::binary); // Binary mode\n\nChecking File Status:\nifstream inFile(\"file.txt\");\nif (!inFile) {\n    cerr << \"Error opening file!\";\n    return 1;\n}\n\nComplete Example (Copy File):\nifstream src(\"source.txt\", ios::binary);\ndest(\"dest.txt\", ios::binary);\n\ndest << src.rdbuf();  // Copy entire file\n\nBest Practices:\n- Always close files (or use RAII)\n- Check if file opened successfully\n- Use getline for text files\n- Use binary mode for non-text files",
    difficulty: "intermediate",
    estimatedMinutes: 10,
    topic: "file-io",
  },
  {
    id: "stl",
    subject: "cpp",
    title: "STL",
    content: "The Standard Template Library (STL) provides ready-to-use data structures and algorithms.\n\nSTL Components:\n1. Containers: store data (vector, map, set, etc.)\n2. Algorithms: operate on containers (sort, find, etc.)\n3. Iterators: traverse containers\n\nVector (Dynamic Array):\n#include <vector>\nvector<int> v = {5, 2, 8, 1, 9};\n\nv.push_back(3);      // Add to end\nv.pop_back();        // Remove from end\nv.size();            // Number of elements\nv[0];                // Access by index\nv.at(1);             // Bounds-checked access\nv.front();           // First element\nv.back();            // Last element\nv.empty();           // Is it empty?\nv.clear();           // Remove all elements\n\nAlgorithms:\n#include <algorithm>\nsort(v.begin(), v.end());        // Sort ascending\nsort(v.begin(), v.end(), greater<int>());  // Sort descending\nreverse(v.begin(), v.end());     // Reverse\nauto it = find(v.begin(), v.end(), 8);  // Find element\nint count = std::count(v.begin(), v.end(), 5);  // Count\n\nOther Containers:\n- deque: double-ended queue\n- list: doubly-linked list\n- set: sorted unique elements\n- map: sorted key-value pairs\n- unordered_map: hash map (faster lookup)\n- stack: LIFO\n- queue: FIFO\n- priority_queue: priority-based queue",
    difficulty: "intermediate",
    estimatedMinutes: 15,
    topic: "stl",
  },
  {
    id: "vector",
    subject: "cpp",
    title: "vector",
    content: "std::vector is the most commonly used STL container — a dynamic array.\n\n#include <vector>\n\nDeclaring Vectors:\nvector<int> v1;                    // Empty\nvector<int> v2(5);                 // 5 elements, all 0\nvector<int> v3(5, 10);            // 5 elements, all 10\nvector<int> v4 = {1, 2, 3, 4, 5}; // Initialized\nvector<int> v5(v4);               // Copy of v4\n\nAdding and Removing:\nv.push_back(10);    // Add to end: {10}\nv.pop_back();       // Remove from end\nv.insert(v.begin(), 0);  // Insert at beginning\nv.erase(v.begin());      // Remove first element\nv.resize(10);       // Resize to 10 elements\n\nAccessing Elements:\nv[0];           // First element (no bounds check)\nv.at(1);        // Second element (bounds checked)\nv.front();      // First element\nv.back();       // Last element\nv.data();       // Pointer to underlying array\n\nSize and Capacity:\nv.size();       // Number of elements\nv.capacity();   // Allocated space\nv.empty();      // Is it empty?\nv.shrink_to_fit();  // Reduce capacity to size\n\nIteration:\n// Index-based\nfor (int i = 0; i < v.size(); i++) {\n    cout << v[i];\n}\n\n// Range-based (preferred)\nfor (int x : v) {\n    cout << x;\n}\n\n// Const reference (for large objects)\nfor (const string& s : vec) {\n    cout << s;\n}\n\nPerformance Tips:\n- Use reserve() if you know the size: v.reserve(1000)\n- Use emplace_back() instead of push_back() for complex objects\n- Prefer range-based for loops",
    difficulty: "intermediate",
    estimatedMinutes: 12,
    topic: "stl",
  },
  {
    id: "dynamic-memory-allocation",
    subject: "cpp",
    title: "Dynamic Memory Allocation",
    content: "Dynamic memory allocation creates variables at runtime (on the heap).\n\nWhy Dynamic Memory?\n- Size determined at runtime\n- Lifetime extends beyond scope\n- Essential for data structures (linked lists, trees)\n\nnew and delete:\nint* p = new int;       // Allocate one int\n*p = 42;               // Assign value\ndelete p;              // Free memory\np = nullptr;           // Good practice\n\nnew[] and delete[]:\nint* arr = new int[100];  // Allocate array of 100 ints\narr[0] = 42;\ndelete[] arr;            // Free array\narr = nullptr;\n\nHeap vs Stack:\nStack:\n- Automatic allocation and deallocation\n- Fast (simple pointer adjustment)\n- Limited size (usually 1-8 MB)\n- Variables go out of scope automatically\n\nHeap:\n- Manual allocation (new) and deallocation (delete)\n- Slower (requires system calls)\n- Large size (limited by RAM)\n- Must explicitly free memory\n\nMemory Leaks:\nvoid leak() {\n    int* p = new int(42);\n    return;  // p is lost, memory leaked!\n}\n\nFix:\nvoid safe() {\n    int* p = new int(42);\n    delete p;  // Free memory\n    p = nullptr;\n}\n\nWhen to Use Dynamic Memory:\n- Array size unknown at compile time\n- Data that must persist beyond scope\n- Large data that would overflow the stack",
    difficulty: "intermediate",
    estimatedMinutes: 12,
    topic: "dynamic-memory",
  },
  {
    id: "smart-pointers",
    subject: "cpp",
    title: "Smart Pointers",
    content: "Smart pointers automatically manage dynamic memory, preventing leaks.\n\n#include <memory>\n\nThree Types:\n\n1. unique_ptr (most common):\n   - Single owner\n   - Cannot be copied\n   - Automatically deleted when out of scope\n\nunique_ptr<int> p1 = make_unique<int>(42);\nunique_ptr<int> p2 = p1;  // Error: cannot copy\nunique_ptr<int> p3 = std::move(p1);  // OK: transfer ownership\n// p1 is now nullptr, p3 owns the memory\n\n2. shared_ptr:\n   - Multiple owners\nn   - Reference counted\n   - Memory deleted when last owner dies\n\nshared_ptr<int> p1 = make_shared<int>(42);\nshared_ptr<int> p2 = p1;  // OK: shared ownership\n// Both p1 and p2 point to the same memory\n// Memory deleted when both go out of scope\n\n3. weak_ptr:\n   - Non-owning reference to shared_ptr\n   - Does not prevent deletion\n   - Use to break circular references\n\nweak_ptr<int> wp = sp;  // sp is a shared_ptr\nif (auto sp2 = wp.lock()) {\n    // Object still alive\n    cout << *sp2;\n}\n\nBest Practices:\n- Prefer stack allocation when possible\n- Use unique_ptr by default\n- Use shared_ptr only when you need shared ownership\n- Never use raw new/delete in modern C++",
    difficulty: "advanced",
    estimatedMinutes: 12,
    topic: "dynamic-memory",
  },
  {
    id: "raii-pattern",
    subject: "cpp",
    title: "RAII Pattern",
    content: "RAII (Resource Acquisition Is Initialization) ties resource lifetime to object lifetime.\n\nThe Principle:\n- Acquire resource in constructor\n- Release resource in destructor\n- Object lifetime manages resource lifetime\n\nWhy RAII?\n- Prevents resource leaks (memory, files, sockets)\n- Exception-safe (cleanup happens automatically)\n- Clear ownership semantics\n\nExample without RAII:\nvoid process() {\n    int* data = new int[1000];\n    // ... do work ...\n    if (error) throw runtime_error(\"Failed\");  // Memory leak!\n    delete[] data;\n}\n\nExample with RAII:\nclass Buffer {\n    int* data;\npublic:\n    Buffer(size_t size) : data(new int[size]) {}\n    ~Buffer() { delete[] data; }\n};\n\nvoid process() {\n    Buffer buf(1000);\n    // ... do work ...\n    if (error) throw runtime_error(\"Failed\");  // No leak!\n    // buf destructor called automatically\n}\n\nRAII in Standard Library:\n- lock_guard: mutex lock/unlock\n- unique_ptr: heap memory\n- fstream: file open/close\n- vector: dynamic array\n\nRule: If you acquire it, wrap it in RAII.",
    difficulty: "advanced",
    estimatedMinutes: 10,
    topic: "dynamic-memory",
  },
  {
    id: "memory-leaks-and-detection",
    subject: "cpp",
    title: "Memory Leaks and Detection",
    content: "A memory leak occurs when allocated memory is never freed.\n\nCommon Causes:\n1. Forgetting to delete:\nvoid leak() {\n    int* p = new int(42);\n    // No delete -> leak\n}\n\n2. Exception before delete:\nvoid leak() {\n    int* p = new int(42);\n    throw runtime_error(\"Error\");  // delete never reached\n}\n\n3. Lost pointer:\nint* p = new int(42);\np = new int(100);  // Old memory leaked\n\n4. Circular reference (shared_ptr):\nshared_ptr<Node> a = make_shared<Node>();\nshared_ptr<Node> b = make_shared<Node>();\na->next = b;\nb->next = a;  // Reference count never reaches 0\n\nDetection Tools:\n1. Valgrind (Linux/Mac):\n   valgrind --leak-check=full ./program\n\n2. Visual Studio (Windows):\n   Debug -> Memory Usage (built-in leak detector)\n\n3. AddressSanitizer:\n   g++ -fsanitize=address -g program.cpp\n\n4. Windows CRT Debug Heap:\n   #define _CRTDBG_MAP_ALLOC\n   #include <stdlib.h>\n   #include <crtdbg.h>\n   // At program end: _CrtDumpMemoryLeaks();\n\nPrevention:\n- Use smart pointers (unique_ptr, shared_ptr)\n- Use RAII for all resources\n- Avoid raw new/delete\n- Initialize pointers to nullptr\n- Set pointers to nullptr after delete",
    difficulty: "advanced",
    estimatedMinutes: 12,
    topic: "dynamic-memory",
  },
  {
    id: "common-memory-mistakes",
    subject: "cpp",
    title: "Common Memory Mistakes",
    content: "Top memory mistakes and how to avoid them:\n\n1. Double Free:\nint* p = new int(42);\ndelete p;\ndelete p;  // Undefined behavior!\n\nFix: set p = nullptr after delete\n\n2. Use After Free:\nint* p = new int(42);\ndelete p;\n*p = 10;  // Undefined behavior!\n\nFix: set p = nullptr after delete\n\n3. Memory Leak:\nvoid leak() {\n    int* p = new int[1000];\n    // Forgot delete[]\n}\n\nFix: use vector instead of new[]\n\n4. Dangling Pointer:\nint* p;\n{\n    int x = 10;\n    p = &x;\n}  // x destroyed\n*p = 20;  // Undefined behavior!\n\nFix: use references or smart pointers\n\n5. Buffer Overflow:\nint arr[5] = {1, 2, 3, 4, 5};\narr[10] = 42;  // Out of bounds!\n\nFix: use vector with .at() for bounds checking\n\n6. Uninitialized Memory:\nint* p = new int;\ncout << *p;  // Garbage value!\n\nFix: initialize: new int(0) or new int{}\n\n7. Mismatched new/delete:\nint* p = new int[100];\ndelete p;    // Wrong! Should be delete[]\n\nFix: match new[] with delete[], new with delete\n\nBest Practice: prefer stack allocation and smart pointers.",
    difficulty: "advanced",
    estimatedMinutes: 10,
    topic: "dynamic-memory",
  },
  {
    id: "function-templates",
    subject: "cpp",
    title: "Function Templates",
    content: "Templates let you write generic code that works with any type.\n\nBasic Template:\ntemplate <typename T>\nT getMax(T a, T b) {\n    return (a > b) ? a : b;\n}\n\n// Usage\nint main() {\n    cout << getMax(5, 10);        // 10 (int)\n    cout << getMax(3.14, 2.72);   // 3.14 (double)\n    cout << getMax('a', 'z');     // z (char)\n    // Type is deduced from arguments\n}\n\nExplicit Type Specification:\ncout << getMax<double>(5, 10);  // Forces double\n\nMultiple Template Parameters:\ntemplate <typename T, typename U>\nauto add(T a, U b) -> decltype(a + b) {\n    return a + b;\n}\n\nFunction Template Overloading:\ntemplate <typename T>\nvoid print(T x) {\n    cout << x;\n}\n\ntemplate <typename T>\nvoid print(T* p) {  // Overload for pointers\n    cout << *p;\n}\n\nHow Templates Work:\n1. Compiler sees template usage\n2. Generates specific code for the type used\n3. Compiles the generated code\n\n// Template definition\ntemplate <typename T>\nT getMax(T a, T b) { return (a > b) ? a : b; }\n\n// Compiler generates:\n// int getMax(int a, int b) { ... }\n// double getMax(double a, double b) { ... }\n// char getMax(char a, char b) { ... }\n\nTemplates are compile-time: no runtime overhead.",
    difficulty: "advanced",
    estimatedMinutes: 12,
    topic: "templates",
  },
  {
    id: "class-templates",
    subject: "cpp",
    title: "Class Templates",
    content: "Class templates create classes that work with any type.\n\nBasic Class Template:\ntemplate <typename T>\nclass Stack {\n    vector<T> elements;\npublic:\n    void push(const T& elem) { elements.push_back(elem); }\n    T pop() {\n        T elem = elements.back();\n        elements.pop_back();\n        return elem;\n    }\n    bool empty() const { return elements.empty(); }\n};\n\n// Usage\nStack<int> intStack;\nintStack.push(10);\nintStack.push(20);\ncout << intStack.pop();  // 20\n\nStack<string> stringStack;\nstringStack.push(\"Hello\");\nstringStack.push(\"World\");\ncout << stringStack.pop();  // World\n\nMultiple Type Parameters:\ntemplate <typename K, typename V>\nclass Pair {\n    K key;\n    V value;\npublic:\n    Pair(const K& k, const V& v) : key(k), value(v) {}\n    K getKey() const { return key; }\n    V getValue() const { return value; }\n};\n\nPair<string, int> p(\"age\", 25);\ncout << p.getKey() << \": \" << p.getValue();\n\nNon-Type Template Parameters:\ntemplate <typename T, int Size>\nclass FixedArray {\n    T arr[Size];\npublic:\n    T& operator[](int i) { return arr[i]; }\n};\n\nFixedArray<int, 10> arr;  // Array of exactly 10 ints\narr[0] = 42;\n\nTemplate Specialization:\ntemplate <>\nclass Stack<bool> {\n    // Special version for bool\n};",
    difficulty: "advanced",
    estimatedMinutes: 12,
    topic: "templates",
  },
  {
    id: "template-specialization",
    subject: "cpp",
    title: "Template Specialization",
    content: "Template specialization provides a different implementation for specific types.\n\nWhy Specialize?\nThe generic template might not work well for certain types.\n\nExample: Generic Print\ntemplate <typename T>\nvoid print(T x) {\n    cout << x;\n}\n\n// Specialization for bool\ntemplate <>\nvoid print<bool>(bool x) {\n    cout << (x ? \"true\" : \"false\");\n}\n\n// Usage\nprint(42);        // Uses generic: prints 42\nprint(true);      // Uses specialization: prints \"true\"\n\nPartial Specialization:\ntemplate <typename T>\nclass Printer {\n    T value;\npublic:\n    void print() { cout << value; }\n};\n\n// Partial specialization for pointers\ntemplate <typename T>\nclass Printer<T*> {\n    T* ptr;\npublic:\n    void print() { cout << *ptr; }\n};\n\n// Usage\nPrinter<int> p1;       // Uses generic version\nPrinter<int*> p2;      // Uses pointer specialization\n\nNon-Type Specialization:\ntemplate <int N>\nstruct Factorial {\n    static constexpr int value = N * Factorial<N-1>::value;\n};\n\ntemplate <>\nstruct Factorial<0> {\n    static constexpr int value = 1;\n};\n\nconstexpr int f5 = Factorial<5>::value;  // 120\n\nWhen to Specialize:\n- Type-specific behavior needed\n- Performance optimization for common types\n- Correctness for types where generic version fails",
    difficulty: "advanced",
    estimatedMinutes: 12,
    topic: "templates",
  },
  {
    id: "variadic-templates",
    subject: "cpp",
    title: "Variadic Templates",
    content: "Variadic templates accept a variable number of template parameters.\n\nBasic Syntax:\ntemplate <typename... Args>\nvoid print(Args... args) {\n    // args is a parameter pack\n}\n\nRecursive Expansion:\ntemplate <typename T>\nvoid print(T x) {\n    cout << x << endl;  // Base case\n}\n\ntemplate <typename T, typename... Args>\nvoid print(T first, Args... rest) {\n    cout << first << \" \";\n    print(rest...);  // Recursive case\n}\n\n// Usage\nprint(1, 2.5, \"hello\", 'A');  // 1 2.5 hello A\n\nFold Expressions (C++17):\ntemplate <typename... Args>\nauto sum(Args... args) {\n    return (args + ...);  // Left fold\n}\n\ncout << sum(1, 2, 3, 4);  // 10\n\nPerfect Forwarding:\ntemplate <typename... Args>\nauto makeString(Args&&... args) {\n    return std::string(std::forward<Args>(args)...);\n}\n\n// Usage\nauto s = makeString(\"Hello\", \" \", \"World\");\n\nWhen to Use:\n- Print functions with any number of arguments\n- Tuple manipulation\n- Type-safe printf alternatives\n- Generic factory functions\n\nCommon Pitfalls:\n- Compile-time code bloat\n- Complex error messages\n- Recursive templates have depth limits",
    difficulty: "advanced",
    estimatedMinutes: 12,
    topic: "templates",
  },
  {
    id: "concepts-cpp20",
    subject: "cpp",
    title: "Concepts (C++20)",
    content: "Concepts constrain template parameters, making code more readable.\n\nBefore Concepts:\ntemplate <typename T>\nT add(T a, T b) {\n    return a + b;  // Fails if T doesn't support +\n}\n\nWith Concepts:\n#include <concepts>\n\ntemplate <typename T>\nconcept Addable = requires(T a, T b) {\n    { a + b } -> std::convertible_to<T>;\n};\n\ntemplate <Addable T>\nT add(T a, T b) {\n    return a + b;\n}\n\n// Or shorter syntax\ntemplate <Addable T>\nT add(T a, T b) { return a + b; }\n\n// Or even shorter\nAddable auto add(Addable auto a, Addable auto b) {\n    return a + b;\n}\n\nBuilt-in Concepts:\n#include <concepts>\n\nstd::integral auto x = 42;      // Must be int, char, etc.\nstd::floating_point auto y = 3.14;  // Must be float, double\nstd::copyable auto v = vec;    // Must be copyable\nstd::sortable auto v = vec;    // Must be sortable\n\nDefining Your Own Concepts:\ntemplate <typename T>\nconcept Printable = requires(T x) {\n    { std::cout << x } -> std::same_as<std::ostream&>;\n};\n\ntemplate <Printable T>\nvoid print(const T& x) {\n    std::cout << x << std::endl;\n}\n\nBenefits:\n- Better error messages\n- Self-documenting code\n- Enforces contracts at compile time\n- Replaces SFINAE in most cases",
    difficulty: "advanced",
    estimatedMinutes: 12,
    topic: "templates",
  },
  {
    id: "auto-keyword",
    subject: "cpp",
    title: "auto Keyword",
    content: "The auto keyword lets the compiler deduce the type automatically.\n\nBasic Usage:\nauto x = 42;        // int\nauto y = 3.14;      // double\nauto s = \"hello\";   // const char*\nauto z = 5.0f;      // float\n\nWhen auto is Useful:\nauto it = v.begin();  // Complex iterator type\nauto lambda = [](int x) { return x * 2; };  // Lambda type\nauto result = func();  // Unknown return type\n\nauto with References:\nauto& ref = x;     // Reference to x\nconst auto& cref = x;  // Const reference\n\nauto with Pointers:\nauto p = &x;        // int*\nauto sp = make_shared<int>(42);  // shared_ptr<int>\n\nauto for Loop:\nauto nums = {1, 2, 3, 4, 5};\nfor (auto x : nums) {\n    cout << x;\n}\n\nStructured Bindings (C++17):\nauto [name, age] = pair(\"Alice\", 20);\nauto [x, y, z] = tuple(1, 2.0, \"three\");\n\nWhen NOT to Use auto:\n- When type is not obvious from context\n- When you need a specific type\n- In function signatures (use explicit types)\n\n// Bad: what type is x?\nauto x = func();\n\n// Good: type is obvious\nauto v = vector<int>(10);  // Obviously vector<int>\nauto it = v.begin();      // Obviously iterator",
    difficulty: "intermediate",
    estimatedMinutes: 8,
    topic: "modern-cpp",
  },
  {
    id: "range-based-for-loop",
    subject: "cpp",
    title: "Range-based for Loop",
    content: "The range-based for loop simplifies iteration over containers.\n\nBasic Syntax:\nint arr[] = {1, 2, 3, 4, 5};\nfor (int x : arr) {\n    cout << x << \" \";\n}\n// Output: 1 2 3 4 5\n\nWith Vector:\nvector<int> v = {10, 20, 30};\nfor (int x : v) {\n    cout << x << \" \";\n}\n\nWith Strings:\nstring s = \"Hello\";\nfor (char c : s) {\n    cout << c << \" \";\n}\n// Output: H e l l o\n\nWith Maps:\nmap<string, int> m = {{\"a\", 1}, {\"b\", 2}};\nfor (const auto& [key, value] : m) {\n    cout << key << \": \" << value << \", \";\n}\n// Output: a: 1, b: 2,\n\nModifying Elements (Use Reference):\nvector<int> v = {1, 2, 3, 4, 5};\nfor (int& x : v) {\n    x *= 2;  // Doubles each element\n}\n// v is now {2, 4, 6, 8, 10}\n\nConst Reference (Avoid Copying):\nvector<string> words = {\"hello\", \"world\"};\nfor (const string& word : words) {\n    cout << word;\n}\n\nInitializer List:\nfor (int x : {1, 2, 3, 4, 5}) {\n    cout << x;\n}\n\nWhen to Use:\n- Simple iteration over all elements\n- When you don't need the index\n- When you don't need to modify the container\n\nWhen NOT to Use:\n- When you need the index (use traditional for)\n- When modifying the container during iteration",
    difficulty: "intermediate",
    estimatedMinutes: 8,
    topic: "modern-cpp",
  },
  {
    id: "lambda-expressions",
    subject: "cpp",
    title: "Lambda Expressions",
    content: "Lambdas are anonymous functions (C++11).\n\nBasic Syntax:\nauto greet = []() { cout << \"Hello!\"; };\ngreet();  // Prints Hello!\n\nCapture Variables:\nint x = 10;\nauto add = [x](int y) { return x + y; };\ncout << add(5);  // 15\n\nCapture Modes:\n[x]    - Capture x by value\n[&x]   - Capture x by reference\n[=]    - Capture all variables by value\n[&]    - Capture all variables by reference\n[=, &x] - All by value, x by reference\n\nLambda with STL:\nvector<int> v = {5, 2, 8, 1, 9};\n\n// Sort ascending\nsort(v.begin(), v.end(), [](int a, int b) {\n    return a < b;\n});\n\n// Sort by absolute value\nsort(v.begin(), v.end(), [](int a, int b) {\n    return abs(a) < abs(b);\n});\n\n// Find first even\nauto it = find_if(v.begin(), v.end(), [](int x) {\n    return x % 2 == 0;\n});\n\n// For each\nfor_each(v.begin(), v.end(), [](int& x) {\n    x *= 2;\n});\n\nMutable Lambdas:\nint count = 0;\nauto inc = [count]() mutable { return ++count; };\ninc(); inc(); inc();\ncout << count;  // 0 (captured by value)\n\nReturn Type:\nauto divide = [](int a, int b) -> double {\n    return static_cast<double>(a) / b;\n};\n\nWhen to Use:\n- Short callbacks (sort, find_if)\n- Event handlers\n- Inline function objects\n- STL algorithm predicates",
    difficulty: "intermediate",
    estimatedMinutes: 12,
    topic: "modern-cpp",
  },
  {
    id: "move-semantics",
    subject: "cpp",
    title: "Move Semantics",
    content: "Move semantics transfer resources instead of copying them.\n\nThe Problem:\nstring createString() {\n    string s = \"Hello World\";\n    return s;  // Copy? Expensive!\n}\n\nThe Solution (Move Semantics):\nstring createString() {\n    string s = \"Hello World\";\n    return std::move(s);  // Move: transfers ownership\n}\n\nstd::move:\n- Casts an object to an rvalue reference\n- Enables move constructor/assignment\n- Source object is left in valid-but-unspecified state\n\nExample:\nvector<int> createVector() {\n    vector<int> v = {1, 2, 3, 4, 5};\n    return v;  // Move (not copy) due to NRVO\n}\n\nMove Constructor:\nclass Buffer {\n    int* data;\n    size_t size;\npublic:\n    // Move constructor\n    Buffer(Buffer&& other) noexcept\n        : data(other.data), size(other.size) {\n        other.data = nullptr;\n        other.size = 0;\n    }\n};\n\nWhen to Use std::move:\n- Transferring ownership of large objects\n- Returning local objects from functions\n- Pushing into containers\n\nWhen NOT to Use std::move:\n- Return values (prevents NRVO)\n- Const objects (falls back to copy)\n- Small objects (copy is cheaper)",
    difficulty: "advanced",
    estimatedMinutes: 12,
    topic: "modern-cpp",
  },
  {
    id: "structured-bindings",
    subject: "cpp",
    title: "Structured Bindings",
    content: "Structured bindings decompose aggregates into named variables (C++17).\n\nBasic Usage:\nauto [x, y, z] = std::tuple{1, 2.0, \"three\"};\ncout << x << \", \" << y << \", \" << z;\n// 1, 2, three\n\nWith Pairs:\nstd::pair<string, int> p = {\"Alice\", 25};\nauto [name, age] = p;\ncout << name << \": \" << age;\n// Alice: 25\n\nWith Maps:\nstd::map<string, int> scores = {{\"Alice\", 95}, {\"Bob\", 87}};\nfor (const auto& [name, score] : scores) {\n    cout << name << \": \" << score;\n}\n\nWith Arrays:\nint arr[3] = {1, 2, 3};\nauto [a, b, c] = arr;\ncout << a << b << c;  // 123\n\nWith Structs:\nstruct Point { double x, y, z; };\nPoint p{1.0, 2.0, 3.0};\nauto [x, y, z] = p;\n\nWith Functions Returning Structs:\nstruct Result { bool success; string message; };\nResult getResult() { return {true, \"OK\"}; }\n\nauto [ok, msg] = getResult();\nif (ok) cout << msg;\n\nWithout Structured Bindings:\nstd::pair<string, int> p = {\"Alice\", 25};\nstring name = p.first;\nint age = p.second;\n\nWith Structured Bindings:\nauto [name, age] = p;  // Cleaner!\n\nBenefits:\n- More readable code\n- Less error-prone (no .first/.second)\n- Works with any aggregate type",
    difficulty: "intermediate",
    estimatedMinutes: 8,
    topic: "modern-cpp",
  },
  {
    id: "naming-conventions",
    subject: "cpp",
    title: "Naming Conventions",
    content: "Consistent naming makes code readable and maintainable.\n\nC++ Naming Conventions:\n\nPascalCase: StudentBankAccount, calculateArea\n- Use for: classes, structs, enums, functions, namespaces\n\ncamelCase: studentCount, calculateTotal\n- Use for: variables, functions, parameters\n\nUPPER_SNAKE_CASE: MAX_SIZE, PI, DEFAULT_TIMEOUT\n- Use for: constants, macros\n\nsnake_case: student_bank_account, calculate_area\n- Use for: variables, functions (alternative style)\n\nHungarian Notation: iCount, szName, pPointer\n- Avoid: redundant with types, hard to read\n\nExamples:\nclass StudentManager {           // PascalCase\n    int studentCount;             // camelCase\n    const int MAX_STUDENTS = 30;  // UPPER_SNAKE_CASE\n\n    void calculateAverage() {     // camelCase\n        double total = 0;          // camelCase\n        for (int i = 0; i < studentCount; i++) {  // camelCase\n            total += students[i].gpa;\n        }\n    }\n};\n\nNaming Tips:\n- Be descriptive: studentCount (not sc)\n- Use nouns for variables: student, score, index\n- Use verbs for functions: calculate, print, validate\n- Avoid abbreviations: count (not cnt)\n- Be consistent across your project\n\nFile Naming:\n- PascalCase for classes: StudentManager.cpp\n- snake_case for utilities: string_utils.cpp\n- Match header and source files",
    difficulty: "intermediate",
    estimatedMinutes: 8,
    topic: "advanced",
  },
  {
    id: "code-organization",
    subject: "cpp",
    title: "Code Organization",
    content: "Organizing code properly makes it maintainable and team-friendly.\n\nFile Structure:\nproject/\n├── src/\n│   ├── main.cpp           # Entry point\n│   ├── student.h          # Class declarations\n│   ├── student.cpp        # Class implementations\n│   ├── utils.h            # Utility functions\n│   └── utils.cpp          # Utility implementations\n├── include/               # Public headers\n├── tests/                 # Unit tests\n├── docs/                  # Documentation\n└── Makefile               # Build system\n\nHeader Files (.h):\n- Declare classes, functions, constants\n- Include guards or #pragma once\n- Minimal includes (forward declare when possible)\n\n// student.h\n#pragma once\n#include <string>\n\nclass Student {\n    std::string name;\n    int age;\npublic:\n    Student(const std::string& name, int age);\n    void display() const;\n    const std::string& getName() const;\n};\n\nSource Files (.cpp):\n- Implement declared functions\n- Include own header first\n#include \"student.h\"\n#include <iostream>\n\nStudent::Student(const std::string& n, int a) : name(n), age(a) {}\n\nvoid Student::display() const {\n    std::cout << name << \", \" << age;\n}\n\nInclude Order:\n1. Corresponding header (student.cpp includes student.h)\n2. C system headers\n3. C++ standard library\n4. Other libraries\n5. Project headers\n\nForward Declaration:\n// Instead of #include \"HeavyClass.h\"\nclass HeavyClass;  // Forward declare\nvoid process(HeavyClass& obj);  // Use reference/pointer",
    difficulty: "intermediate",
    estimatedMinutes: 10,
    topic: "advanced",
  },
  {
    id: "error-handling-patterns",
    subject: "cpp",
    title: "Error Handling Patterns",
    content: "Choose the right error handling strategy for the situation.\n\nPattern 1: Exception (Exceptional Cases)\ndouble divide(int a, int b) {\n    if (b == 0) throw std::invalid_argument(\"Division by zero\");\n    return static_cast<double>(a) / b;\n}\n\ntry {\n    double result = divide(10, 0);\n} catch (const std::exception& e) {\n    std::cerr << e.what();\n}\n\nPattern 2: Return Code (Expected Failures)\nenum class Error { OK, NOT_FOUND, INVALID_INPUT };\n\nError findUser(int id, User& result) {\n    if (id < 0) return Error::INVALID_INPUT;\n    // search...\n    return Error::NOT_FOUND;\n}\n\nPattern 3: std::expected (C++23)\nstd::expected<int, std::string> parse(std::string s) {\n    if (s.empty()) return std::unexpected(\"Empty input\");\n    return std::stoi(s);\n}\n\nPattern 4: Optional (Maybe Value)\nstd::optional<int> findMax(const std::vector<int>& v) {\n    if (v.empty()) return std::nullopt;\n    return *std::max_element(v.begin(), v.end());\n}\n\nWhen to Use Which:\n- Exceptions: exceptional conditions, library boundaries\n- Return codes: performance-critical, simple functions\n- expected: expected failures (parsing, validation)\n- optional: value may or may not exist\n\nBest Practices:\n- Don't use exceptions for control flow\n- Use RAII for cleanup\n- Catch by const reference\n- Log errors at the point of handling",
    difficulty: "intermediate",
    estimatedMinutes: 10,
    topic: "advanced",
  },
  {
    id: "performance-tips",
    subject: "cpp",
    title: "Performance Tips",
    content: "C++ is fast by default. These tips keep it that way.\n\n1. Prefer Stack Over Heap:\n// Slow: heap allocation\nint* p = new int(42);\ndelete p;\n\n// Fast: stack allocation\nint x = 42;\n\n2. Use const Reference for Large Objects:\n// Slow: copies entire string\nvoid process(std::string s) { ... }\n\n// Fast: no copy\nvoid process(const std::string& s) { ... }\n\n3. Use Move Semantics:\n// Slow: copies vector\nstd::vector<int> v1 = createVector();\n\n// Fast: moves vector\nstd::vector<int> v2 = std::move(v1);\n\n4. Reserve Vector Capacity:\nstd::vector<int> v;\nv.reserve(10000);  // Pre-allocate\nfor (int i = 0; i < 10000; i++) {\n    v.push_back(i);  // No reallocation\n}\n\n5. Use emplace_back Over push_back:\n// Creates temporary, then copies\nv.push_back(MyClass(args));\n\n// Constructs in-place\nv.emplace_back(args);\n\n6. Avoid Unnecessary Copies:\nfor (const auto& item : collection) {  // const&\n    process(item);\n}\n\n7. Use Algorithms Over Loops:\nstd::sort(v.begin(), v.end());  // Optimized\n\n8. Profile First:\n- Don't optimize without measuring\n- Use a profiler to find actual bottlenecks\n- Focus on hot paths\n\nKnuth's Rule: \"Premature optimization is the root of all evil.\"",
    difficulty: "intermediate",
    estimatedMinutes: 10,
    topic: "advanced",
  },
  {
    id: "code-review-checklist",
    subject: "cpp",
    title: "Code Review Checklist",
    content: "Use this checklist when reviewing or writing code.\n\nCorrectness:\n- Does the code do what it's supposed to do?\n- Are all edge cases handled (empty input, null, overflow)?\n- Are error conditions handled gracefully?\n\nMemory Safety:\n- Are all allocations freed?\n- Are pointers checked before dereferencing?\n- Is there any buffer overflow risk?\n- Are smart pointers used instead of raw new/delete?\n\nPerformance:\n- Are large objects passed by const reference?\n- Are unnecessary copies avoided?\n- Is reserve() used for known-size containers?\n- Are algorithms used instead of manual loops?\n\nReadability:\n- Are variable names descriptive?\n- Is the code well-organized?\n- Are comments used where needed?\n- Is the code consistent with project style?\n\nSecurity:\n- Is input validated?\n- Are buffer sizes checked?\n- Are secrets hardcoded?\n- Are random numbers properly seeded?\n\nTesting:\n- Are there unit tests for the code?\n- Do tests cover edge cases?\n- Is the code testable (loose coupling)?\n\nMaintainability:\n- Is the code modular (single responsibility)?\n- Are dependencies minimal?\n- Is the code documented where needed?\n- Will other developers understand this code?\n\nCommon Review Findings:\n- Missing null checks\n- Uninitialized variables\n- Resource leaks\n- Magic numbers\n- Inconsistent naming\n- Missing const correctness",
    difficulty: "intermediate",
    estimatedMinutes: 10,
    topic: "advanced",
  },
];

