import type { SubjectConfig } from "../types";

export const cppSubject: SubjectConfig = {
  name: "C++",
  slug: "cpp",
  description: "Master C++ from basics to advanced concepts",
  icon: "/cpp.svg",
  topics: [
    { slug: "basics", name: "C++ Basics", description: "Variables, data types, and I/O", count: 20 },
    { slug: "operators", name: "Operators & Expressions", description: "Arithmetic, relational, logical operators", count: 9 },
    { slug: "conditionals", name: "Conditionals", description: "if/else and switch statements", count: 6 },
    { slug: "loops", name: "Loops", description: "for, while, do-while loops", count: 10 },
    { slug: "functions", name: "Functions", description: "Modular code with functions", count: 9 },
    { slug: "arrays-strings", name: "Arrays & Strings", description: "Array manipulation and string handling", count: 10 },
    { slug: "pointers", name: "Pointers & References", description: "Memory addresses and references", count: 7 },
    { slug: "structures", name: "Structures", description: "Custom data types with structs", count: 4 },
    { slug: "oops", name: "Object-Oriented Programming", description: "Classes, objects, inheritance, polymorphism", count: 13 },
    { slug: "file-io", name: "File Handling", description: "Reading from and writing to files", count: 1 },
    { slug: "stl", name: "Standard Template Library", description: "Vectors, containers, and algorithms", count: 8 },
    { slug: "dynamic-memory", name: "Dynamic Memory", description: "Pointers, smart pointers, and memory management", count: 8 },
    { slug: "templates", name: "Templates", description: "Generic programming with templates", count: 8 },
    { slug: "modern-cpp", name: "Modern C++", description: "C++11/17/20 features and best practices", count: 8 },
    { slug: "advanced", name: "Advanced Topics", description: "Best practices, project structure, code review", count: 9 },
  ],
  noteCounts: {
    basics: 20,
    operators: 9,
    conditionals: 6,
    loops: 10,
    functions: 9,
    "arrays-strings": 10,
    pointers: 7,
    structures: 4,
    oops: 13,
    "file-io": 1,
    stl: 8,
    "dynamic-memory": 8,
    templates: 8,
    "modern-cpp": 8,
    advanced: 9,
  },
};
